function [scenario, perturbed_plant, metadata] = ...
        generate_monte_carlo_scenario(run_index, base_seed, config, nominal)
%GENERATE_MONTE_CARLO_SCENARIO Generate one deterministic paired MC case.

validate_run_index(run_index);
validate_base_seed(base_seed);
seed = double(base_seed) + double(run_index);
if seed > 2^32 - 1
    error("twsbr:scenario:invalid_seed", ...
        "The combined Monte Carlo seed must not exceed 2^32-1.");
end
validated_config = validate_config(config);
validated_nominal = validate_nominal(nominal);

stream = RandStream("mt19937ar", "Seed", seed);
rho = validated_config.parameter_rho;
deltas = -rho + 2 * rho .* rand(stream, 1, 3);
initial_theta_deg = draw_range(stream, ...
    validated_config.initial_tilt_deg_range);
reference_amplitude = draw_range(stream, ...
    validated_config.reference_range);
force_magnitude = draw_range(stream, validated_config.force_range);
if mod(double(run_index), 2) == 0
    force_amplitude = force_magnitude;
else
    force_amplitude = -force_magnitude;
end
force_start = draw_range(stream, validated_config.force_start_range);
force_duration = draw_range(stream, ...
    validated_config.force_duration_range);
constant_force = draw_range(stream, ...
    validated_config.constant_force_range);

overrides = validated_nominal;
overrides.body_mass = validated_nominal.body_mass * (1 + deltas(1));
overrides.com_length = validated_nominal.com_length * (1 + deltas(2));
overrides.body_inertia = validated_nominal.body_inertia * (1 + deltas(3));
perturbed_plant = twsbr_params(overrides);

metadata = struct( ...
    "run_index", double(run_index), ...
    "seed", seed, ...
    "rho", rho, ...
    "delta_body_mass", deltas(1), ...
    "delta_com_length", deltas(2), ...
    "delta_body_inertia", deltas(3), ...
    "initial_theta_deg", initial_theta_deg, ...
    "reference_amplitude", reference_amplitude, ...
    "force_amplitude", force_amplitude, ...
    "force_start", force_start, ...
    "force_duration", force_duration, ...
    "constant_force", constant_force, ...
    "measurement_noise_seed", seed);

reference_start = validated_config.reference_start;
disturbance_end = force_start + force_duration;
x_reference = @(time) reference_amplitude .* ...
    double(time >= reference_start);
force_disturbance = @(time) constant_force + force_amplitude .* ...
    double(time >= force_start & time < disturbance_end);
torque_disturbance = @(time) zeros(size(time));
scenario = struct( ...
    "name", "S4_monte_carlo", ...
    "split", "test", ...
    "duration", validated_config.duration, ...
    "initial_state", [0; 0; deg2rad(initial_theta_deg); 0], ...
    "x_reference", x_reference, ...
    "force_disturbance", force_disturbance, ...
    "torque_disturbance", torque_disturbance, ...
    "reference_start", reference_start, ...
    "disturbance_end", disturbance_end, ...
    "measurement_noise_std", validated_config.noise_std, ...
    "reference_amplitude", reference_amplitude, ...
    "force_amplitude", force_amplitude, ...
    "force_start", force_start, ...
    "force_duration", force_duration, ...
    "torque_amplitude", 0, ...
    "torque_start", 0, ...
    "torque_duration", 0, ...
    "constant_force", constant_force);
end

function validate_run_index(run_index)
if ~is_nonnegative_integer(run_index) || double(run_index) > 2^32 - 1
    error("twsbr:scenario:invalid_run_index", ...
        "Run index must be a nonnegative integer no greater than 2^32-1.");
end
end

function validate_base_seed(base_seed)
if ~is_nonnegative_integer(base_seed) || double(base_seed) > 2^32 - 1
    error("twsbr:scenario:invalid_base_seed", ...
        "Base seed must be a nonnegative integer no greater than 2^32-1.");
end
end

function valid = is_nonnegative_integer(value)
valid = isnumeric(value) && isreal(value) && isscalar(value) && ...
    isfinite(value) && value >= 0 && value == floor(value);
end

function validated = validate_config(config)
required_fields = ["parameter_rho"; "duration"; ...
    "initial_tilt_deg_range"; "reference_range"; "reference_start"; ...
    "force_range"; "force_start_range"; "force_duration_range"; ...
    "constant_force_range"; "noise_std"];
if ~isstruct(config) || ~isscalar(config) || ...
        ~all(isfield(config, required_fields))
    invalid_config();
end

rho = config.parameter_rho;
duration = config.duration;
reference_start = config.reference_start;
if ~is_real_finite_scalar(rho) || rho < 0 || rho >= 1 || ...
        ~is_real_finite_scalar(duration) || duration <= 0 || ...
        ~is_real_finite_scalar(reference_start) || reference_start < 0
    invalid_config();
end

range_fields = ["initial_tilt_deg_range"; "reference_range"; ...
    "force_range"; "force_start_range"; "force_duration_range"; ...
    "constant_force_range"];
for index = 1:numel(range_fields)
    if ~is_valid_range(config.(range_fields(index)))
        invalid_config();
    end
end
if any(config.initial_tilt_deg_range < 0) || ...
        any(config.reference_range < 0) || any(config.force_range < 0) || ...
        any(config.force_start_range < 0) || ...
        any(config.force_duration_range <= 0) || ...
        reference_start > duration || ...
        max(config.force_start_range) + ...
            max(config.force_duration_range) > duration
    invalid_config();
end

noise_std = config.noise_std;
if ~isnumeric(noise_std) || ~isreal(noise_std) || ...
        ~isequal(size(noise_std), [4, 1]) || ...
        any(~isfinite(noise_std)) || any(noise_std < 0)
    invalid_config();
end

validated = config;
validated.parameter_rho = double(rho);
validated.duration = double(duration);
validated.reference_start = double(reference_start);
validated.noise_std = double(noise_std);
for index = 1:numel(range_fields)
    field_name = range_fields(index);
    validated.(field_name) = double(config.(field_name));
end
end

function valid = is_valid_range(value)
valid = isnumeric(value) && isreal(value) && isequal(size(value), [1, 2]) && ...
    all(isfinite(value)) && value(1) <= value(2);
end

function valid = is_real_finite_scalar(value)
valid = isnumeric(value) && isreal(value) && isscalar(value) && ...
    isfinite(value);
end

function invalid_config()
error("twsbr:scenario:invalid_config", ...
    "Monte Carlo configuration fields and ranges are invalid.");
end

function validated = validate_nominal(nominal)
required_fields = fieldnames(twsbr_params());
if ~isstruct(nominal) || ~isscalar(nominal) || ...
        ~all(isfield(nominal, required_fields))
    invalid_nominal();
end
try
    validated = nominal;
    nominal_fields = fieldnames(validated);
    for index = 1:numel(nominal_fields)
        field_name = nominal_fields{index};
        if isnumeric(validated.(field_name))
            validated.(field_name) = double(validated.(field_name));
        end
    end
    validated = twsbr_params(validated);
catch
    invalid_nominal();
end
end

function invalid_nominal()
error("twsbr:scenario:invalid_nominal", ...
    "Nominal plant parameters must satisfy the complete plant contract.");
end

function value = draw_range(stream, bounds)
value = bounds(1) + (bounds(2) - bounds(1)) * rand(stream);
end
