function scenarios = heldout_scenarios(duration)
%HELDOUT_SCENARIOS Return the deterministic held-out study scenarios.

validate_duration(duration);

scenarios = struct();
scenarios.S1_initial_tilt_3deg = make_scenario( ...
    "S1_initial_tilt_3deg", duration, [0; 0; deg2rad(3); 0], ...
    0, 0, 0, 0, 0, 0, 0, 0, 0);
scenarios.S1_initial_tilt_6deg = make_scenario( ...
    "S1_initial_tilt_6deg", duration, [0; 0; deg2rad(6); 0], ...
    0, 0, 0, 0, 0, 0, 0, 0, 0);
scenarios.S1_initial_tilt_9deg = make_scenario( ...
    "S1_initial_tilt_9deg", duration, [0; 0; deg2rad(9); 0], ...
    0, 0, 0, 0, 0, 0, 0, 0, 0);
scenarios.S1_initial_tilt_12deg = make_scenario( ...
    "S1_initial_tilt_12deg", duration, [0; 0; deg2rad(12); 0], ...
    0, 0, 0, 0, 0, 0, 0, 0, 0);
scenarios.S2_position_step_0p25m = make_scenario( ...
    "S2_position_step_0p25m", duration, zeros(4, 1), ...
    0.25, 1.0, 0, 0, 0, 0, 0, 0, 0);
scenarios.S2_position_step_0p75m = make_scenario( ...
    "S2_position_step_0p75m", duration, zeros(4, 1), ...
    0.75, 1.0, 0, 0, 0, 0, 0, 0, 0);
scenarios.S2_position_step_1p0m = make_scenario( ...
    "S2_position_step_1p0m", duration, zeros(4, 1), ...
    1.0, 1.0, 0, 0, 0, 0, 0, 0, 0);
scenarios.S2_saturation_stress = make_scenario( ...
    "S2_saturation_stress", duration, [0; 0; deg2rad(8); 0], ...
    1.0, 0.5, 10.0, 1.2, 0.2, 0, 0, 0, 0);
scenarios.S3_positive_impulse = make_scenario( ...
    "S3_positive_impulse", duration, zeros(4, 1), ...
    0.5, 1.0, 8.0, 4.0, 0.2, 0, 0, 0, 0);
scenarios.S3_negative_impulse = make_scenario( ...
    "S3_negative_impulse", duration, zeros(4, 1), ...
    0.5, 1.0, -8.0, 4.0, 0.2, 0, 0, 0, 0);
scenarios.S3_torque_impulse = make_scenario( ...
    "S3_torque_impulse", duration, zeros(4, 1), ...
    0.5, 1.0, 0, 0, 0, 0.9, 4.0, 0.15, 0);
scenarios.S5_constant_bias = make_scenario( ...
    "S5_constant_bias", duration, zeros(4, 1), ...
    0.5, 1.0, 0, 0, 0, 0, 0, 0, 0.8);
end

function validate_duration(duration)
minimum_duration = 4.2;
if ~isnumeric(duration) || ~isreal(duration) || ~isscalar(duration) || ...
        ~isfinite(duration) || duration < minimum_duration
    error("twsbr:scenario:invalid_duration", ...
        "Duration must be a real finite scalar of at least %.1f seconds.", ...
        minimum_duration);
end
end

function scenario = make_scenario(name, duration, initial_state, ...
        reference_amplitude, reference_start, force_amplitude, force_start, ...
        force_duration, torque_amplitude, torque_start, torque_duration, ...
        constant_force)
disturbance_end = max(force_start + force_duration, ...
    torque_start + torque_duration);
x_reference = @(time) reference_amplitude .* double(time >= reference_start);
force_disturbance = @(time) constant_force + force_amplitude .* ...
    double(time >= force_start & time < force_start + force_duration);
torque_disturbance = @(time) torque_amplitude .* ...
    double(time >= torque_start & time < torque_start + torque_duration);

scenario = struct( ...
    "name", name, ...
    "split", "test", ...
    "duration", duration, ...
    "initial_state", initial_state(:), ...
    "x_reference", x_reference, ...
    "force_disturbance", force_disturbance, ...
    "torque_disturbance", torque_disturbance, ...
    "reference_start", reference_start, ...
    "disturbance_end", disturbance_end, ...
    "measurement_noise_std", zeros(4, 1), ...
    "reference_amplitude", reference_amplitude, ...
    "force_amplitude", force_amplitude, ...
    "force_start", force_start, ...
    "force_duration", force_duration, ...
    "torque_amplitude", torque_amplitude, ...
    "torque_start", torque_start, ...
    "torque_duration", torque_duration, ...
    "constant_force", constant_force);
end
