function scenarios = training_scenarios(duration)
%TRAINING_SCENARIOS Return the frozen training-only study scenarios.

validate_duration(duration);

scenarios = struct();
scenarios.T1_initial_tilt_5deg = make_scenario( ...
    "T1_initial_tilt_5deg", duration, [0; 0; deg2rad(5); 0], ...
    0, 0, 0, 0, 0, 0, 0, 0);
scenarios.T2_position_step_0p5m = make_scenario( ...
    "T2_position_step_0p5m", duration, zeros(4, 1), ...
    0.5, 1, 0, 0, 0, 0, 0, 0);
scenarios.T3_impulse_disturbance = make_scenario( ...
    "T3_impulse_disturbance", duration, [0; 0; deg2rad(2); 0], ...
    0, 0, 5, 3, 0.2, 0, 0, 0);
end

function validate_duration(duration)
minimum_duration = 3.2;
if ~isnumeric(duration) || ~isreal(duration) || ~isscalar(duration) || ...
        ~isfinite(duration) || duration < minimum_duration
    error("twsbr:scenario:invalid_duration", ...
        "Duration must be a real finite scalar of at least %.1f seconds.", ...
        minimum_duration);
end
end

function scenario = make_scenario(name, duration, initial_state, ...
        reference_amplitude, reference_start, force_amplitude, force_start, ...
        force_duration, torque_amplitude, torque_start, torque_duration)
metadata = [reference_amplitude, reference_start, force_amplitude, ...
    force_start, force_duration, torque_amplitude, torque_start, ...
    torque_duration];
if any(~isfinite(metadata)) || any(metadata < 0)
    error("twsbr:scenario:invalid_metadata", ...
        "Scenario metadata must contain nonnegative finite values.");
end

constant_force = 0;
disturbance_end = max(force_start + force_duration, ...
    torque_start + torque_duration);
if reference_start > duration || disturbance_end > duration
    error("twsbr:scenario:invalid_duration", ...
        "Duration must contain all reference and disturbance events.");
end

x_reference = @(time) reference_amplitude .* double(time >= reference_start);
force_disturbance = @(time) constant_force + force_amplitude .* ...
    double(time >= force_start & time < force_start + force_duration);
torque_disturbance = @(time) torque_amplitude .* ...
    double(time >= torque_start & time < torque_start + torque_duration);

scenario = struct( ...
    "name", name, ...
    "split", "train", ...
    "duration", duration, ...
    "initial_state", initial_state(:), ...
    "x_reference", x_reference, ...
    "force_disturbance", force_disturbance, ...
    "torque_disturbance", torque_disturbance, ...
    "reference_start", reference_start, ...
    "disturbance_end", disturbance_end, ...
    "measurement_noise_std", zeros(4, 1), ...
    "reference_amplitude", reference_amplitude, ...
    "force_amplitude", force_amplitude, ...
    "force_start", force_start, ...
    "force_duration", force_duration, ...
    "torque_amplitude", torque_amplitude, ...
    "torque_start", torque_start, ...
    "torque_duration", torque_duration, ...
    "constant_force", constant_force);
end
