function model_path = create_lqi_simulink_model( ...
    plant_params, params, plant_model_path, model_path)
%CREATE_LQI_SIMULINK_MODEL Create a fresh sampled full-state LQI model.

model_name = "twsbr_lqi";
plant_model_name = "twsbr_plant";
load_system("simulink");
load_system(plant_model_path);
plant_cleanup = onCleanup(@() close_model_if_loaded(plant_model_name));
new_system(model_name);
model_cleanup = onCleanup(@() close_model_if_loaded(model_name));

set_param(model_name, ...
    "SolverType", "Variable-step", ...
    "Solver", "ode45", ...
    "RelTol", "1e-9", ...
    "AbsTol", "1e-11", ...
    "MaxStep", sprintf("%.17g", params.plant_step), ...
    "StopTime", "8.0", ...
    "ReturnWorkspaceOutputs", "on");

add_block("simulink/Sources/From Workspace", ...
    model_name + "/position_reference", ...
    "VariableName", "position_reference_data", ...
    "Interpolate", "off", ...
    "OutputAfterFinalValue", "Holding final value", ...
    "Position", [25, 50, 145, 80]);
add_block("simulink/Discrete/Zero-Order Hold", ...
    model_name + "/reference_sampling", ...
    "SampleTime", sprintf("%.17g", params.sample_time), ...
    "Position", [185, 50, 245, 80]);
add_block("simulink/Sources/From Workspace", ...
    model_name + "/controller_reset", ...
    "VariableName", "controller_reset_data", ...
    "Interpolate", "off", ...
    "OutputAfterFinalValue", "Holding final value", ...
    "Position", [25, 110, 145, 140]);
add_block("simulink/Discrete/Zero-Order Hold", ...
    model_name + "/reset_sampling", ...
    "SampleTime", sprintf("%.17g", params.sample_time), ...
    "Position", [185, 110, 245, 140]);
add_block("simulink/Discrete/Zero-Order Hold", ...
    model_name + "/state_sampling", ...
    "SampleTime", sprintf("%.17g", params.sample_time), ...
    "Position", [530, 220, 590, 250]);
add_block("simulink/Signal Routing/Demux", model_name + "/state_demux", ...
    "Outputs", "4", "Position", [635, 165, 640, 295]);
add_block("simulink/Math Operations/Sum", model_name + "/position_error", ...
    "Inputs", "+-", "Position", [690, 75, 715, 105]);
add_block("simulink/Discrete/Discrete-Time Integrator", ...
    model_name + "/position_error_integrator", ...
    "IntegratorMethod", "Forward Euler", ...
    "gainval", "1", ...
    "SampleTime", sprintf("%.17g", params.sample_time), ...
    "ExternalReset", "rising", ...
    "InitialCondition", "0.0", ...
    "LimitOutput", "on", ...
    "UpperSaturationLimit", sprintf("%.17g", params.position_integral_limit), ...
    "LowerSaturationLimit", sprintf("%.17g", -params.position_integral_limit), ...
    "Position", [760, 75, 805, 105]);
add_block("simulink/Math Operations/Gain", model_name + "/state_gain", ...
    "Gain", mat2str(-params.state_gain, 17), ...
    "Multiplication", "Matrix(K*u)", "Position", [690, 190, 790, 225]);
add_block("simulink/Math Operations/Gain", model_name + "/integral_gain", ...
    "Gain", mat2str(-params.integral_gain, 17), ...
    "Position", [850, 75, 940, 105]);
add_block("simulink/Math Operations/Sum", model_name + "/controller_sum", ...
    "Inputs", "++", "Position", [980, 120, 1005, 155]);
add_block("simulink/Discontinuities/Saturation", ...
    model_name + "/actuator_saturation", ...
    "UpperLimit", sprintf("%.17g", plant_params.u_max), ...
    "LowerLimit", sprintf("%.17g", -plant_params.u_max), ...
    "Position", [1040, 120, 1095, 155]);
add_block(plant_model_name + "/nonlinear_plant", ...
    model_name + "/nonlinear_plant", "Position", [1190, 190, 1395, 345]);
add_block("simulink/Sources/From Workspace", ...
    model_name + "/disturbance_force", ...
    "VariableName", "disturbance_force_data", ...
    "Interpolate", "off", ...
    "OutputAfterFinalValue", "Holding final value", ...
    "Position", [1040, 240, 1160, 270]);
add_block("simulink/Sources/From Workspace", ...
    model_name + "/disturbance_torque", ...
    "VariableName", "disturbance_torque_data", ...
    "Interpolate", "off", ...
    "OutputAfterFinalValue", "Holding final value", ...
    "Position", [1040, 300, 1160, 330]);
add_block("simulink/Sinks/Out1", model_name + "/state", ...
    "Position", [1495, 210, 1525, 230]);

add_workspace_log(model_name, "state_log", "state_log", [1435, 280, 1525, 310]);
add_workspace_log(model_name, "position_reference_log", ...
    "position_reference_log", [370, 20, 505, 50]);
add_workspace_log(model_name, "position_error_log", ...
    "position_error_log", [710, 20, 830, 50]);
add_workspace_log(model_name, "position_integral_log", ...
    "position_integral_log", [810, 20, 940, 50]);
add_workspace_log(model_name, "u_raw_log", "u_raw_log", [995, 65, 1085, 95]);
add_workspace_log(model_name, "u_log", "u_log", [1105, 120, 1170, 150]);
add_workspace_log(model_name, "disturbance_force_log", ...
    "disturbance_force_log", [1040, 370, 1175, 400]);
add_workspace_log(model_name, "disturbance_torque_log", ...
    "disturbance_torque_log", [1040, 415, 1180, 445]);

add_named_line(model_name, "position_reference/1", ...
    "reference_sampling/1", "position_reference");
add_named_line(model_name, "reference_sampling/1", ...
    "position_error/2", "sampled_position_reference");
add_named_line(model_name, "reference_sampling/1", ...
    "position_reference_log/1", "sampled_position_reference");
add_named_line(model_name, "controller_reset/1", ...
    "reset_sampling/1", "controller_reset");
add_named_line(model_name, "reset_sampling/1", ...
    "position_error_integrator/2", "sampled_controller_reset");
add_named_line(model_name, "nonlinear_plant/1", "state_sampling/1", "state");
add_named_line(model_name, "state_sampling/1", "state_demux/1", "sampled_state");
add_named_line(model_name, "state_sampling/1", "state_gain/1", "sampled_state");
add_named_line(model_name, "state_demux/1", "position_error/1", "sampled_position");
add_named_line(model_name, "position_error/1", ...
    "position_error_integrator/1", "position_error");
add_named_line(model_name, "position_error/1", ...
    "position_error_log/1", "position_error");
add_named_line(model_name, "position_error_integrator/1", ...
    "integral_gain/1", "position_integral");
add_named_line(model_name, "position_error_integrator/1", ...
    "position_integral_log/1", "position_integral");
add_named_line(model_name, "state_gain/1", "controller_sum/1", "state_feedback");
add_named_line(model_name, "integral_gain/1", ...
    "controller_sum/2", "integral_feedback");
add_named_line(model_name, "controller_sum/1", ...
    "actuator_saturation/1", "u_raw");
add_named_line(model_name, "controller_sum/1", "u_raw_log/1", "u_raw");
add_named_line(model_name, "actuator_saturation/1", "nonlinear_plant/1", "u");
add_named_line(model_name, "actuator_saturation/1", "u_log/1", "u");
add_named_line(model_name, "disturbance_force/1", ...
    "nonlinear_plant/2", "disturbance_force");
add_named_line(model_name, "disturbance_force/1", ...
    "disturbance_force_log/1", "disturbance_force");
add_named_line(model_name, "disturbance_torque/1", ...
    "nonlinear_plant/3", "disturbance_torque");
add_named_line(model_name, "disturbance_torque/1", ...
    "disturbance_torque_log/1", "disturbance_torque");
add_named_line(model_name, "nonlinear_plant/1", "state/1", "state");
add_named_line(model_name, "nonlinear_plant/1", "state_log/1", "state");

model_workspace = get_param(model_name, "ModelWorkspace");
default_data = [0.0, 0.0; 8.0, 0.0];
default_reset = [0.0, 1.0; params.plant_step, 0.0; 8.0, 0.0];
assignin(model_workspace, "position_reference_data", default_data);
assignin(model_workspace, "controller_reset_data", default_reset);
assignin(model_workspace, "disturbance_force_data", default_data);
assignin(model_workspace, "disturbance_torque_data", default_data);

set_param(model_name, "SimulationCommand", "update");
save_system(model_name, model_path);
close_system(model_name, 0);
close_system(plant_model_name, 0);
clear model_cleanup plant_cleanup;
end

function add_workspace_log(model_name, block_name, variable_name, position)
add_block("simulink/Sinks/To Workspace", model_name + "/" + block_name, ...
    "VariableName", variable_name, ...
    "SaveFormat", "Structure With Time", ...
    "Position", position);
end

function add_named_line(model_name, source, destination, signal_name)
line_handle = add_line(model_name, source, destination, "autorouting", "on");
set_param(line_handle, "Name", signal_name);
end

function close_model_if_loaded(model_name)
if bdIsLoaded(model_name)
    close_system(model_name, 0);
end
end
