function model_path = create_fuzzy_pid_simulink_model( ...
        plant_params, params, plant_model_path, model_path)
%CREATE_FUZZY_PID_SIMULINK_MODEL Create a fresh sampled fuzzy PID model.

model_name = "twsbr_fuzzy_pid";
plant_model_name = "twsbr_plant";
load_system("simulink");
load_system(plant_model_path);
plant_cleanup = onCleanup(@() close_model_if_loaded(plant_model_name));
new_system(model_name);
model_cleanup = onCleanup(@() close_model_if_loaded(model_name));

set_param(model_name, ...
    "SolverType", "Variable-step", "Solver", "ode45", ...
    "RelTol", "1e-9", "AbsTol", "1e-11", ...
    "MaxStep", sprintf("%.17g", params.plant_step), "StopTime", "8.0", ...
    "ReturnWorkspaceOutputs", "on");

add_block("simulink/Sources/From Workspace", model_name + "/position_reference", ...
    "VariableName", "position_reference_data", "Interpolate", "off", ...
    "OutputAfterFinalValue", "Holding final value", "Position", [25, 45, 145, 75]);
add_block("simulink/Discrete/Zero-Order Hold", model_name + "/reference_sampling", ...
    "SampleTime", sprintf("%.17g", params.sample_time), "Position", [180, 45, 235, 75]);
add_block("simulink/Sources/From Workspace", model_name + "/controller_reset", ...
    "VariableName", "controller_reset_data", "Interpolate", "off", ...
    "OutputAfterFinalValue", "Holding final value", "Position", [25, 100, 145, 130]);
add_block("simulink/Discrete/Zero-Order Hold", model_name + "/reset_sampling", ...
    "SampleTime", sprintf("%.17g", params.sample_time), "Position", [180, 100, 235, 130]);
add_block("simulink/Discrete/Zero-Order Hold", model_name + "/state_sampling", ...
    "SampleTime", sprintf("%.17g", params.sample_time), "Position", [180, 175, 235, 220]);
add_block("simulink/User-Defined Functions/MATLAB Function", model_name + "/fuzzy_controller", ...
    "Position", [300, 55, 490, 335]);
add_block("simulink/Discontinuities/Saturation", model_name + "/actuator_saturation", ...
    "UpperLimit", sprintf("%.17g", plant_params.u_max), ...
    "LowerLimit", sprintf("%.17g", -plant_params.u_max), "Position", [535, 70, 590, 110]);
add_block(plant_model_name + "/nonlinear_plant", model_name + "/nonlinear_plant", ...
    "Position", [690, 125, 895, 280]);
add_block("simulink/Sources/From Workspace", model_name + "/disturbance_force", ...
    "VariableName", "disturbance_force_data", "Interpolate", "off", ...
    "OutputAfterFinalValue", "Holding final value", "Position", [515, 190, 635, 220]);
add_block("simulink/Sources/From Workspace", model_name + "/disturbance_torque", ...
    "VariableName", "disturbance_torque_data", "Interpolate", "off", ...
    "OutputAfterFinalValue", "Holding final value", "Position", [515, 250, 635, 280]);
add_block("simulink/Signal Routing/Demux", model_name + "/state_demux", ...
    "Outputs", "4", "Position", [935, 120, 940, 285]);
add_block("simulink/Sinks/Out1", model_name + "/state", "Position", [1010, 315, 1040, 335]);

controller_chart = find_chart(model_name + "/fuzzy_controller");
if isempty(controller_chart)
    error("twsbr:simulink:function_block_not_found", ...
        "Could not configure the fuzzy controller MATLAB Function block.");
end
controller_chart.Script = char(make_controller_script(params));

add_workspace_log(model_name, "state_log", "state_log", [925, 335, 1015, 365]);
add_workspace_log(model_name, "position_reference_log", "position_reference_log", [255, 15, 390, 45]);
add_workspace_log(model_name, "position_error_log", "position_error_log", [500, 350, 620, 380]);
add_workspace_log(model_name, "theta_reference_log", "theta_reference_log", [500, 395, 635, 425]);
add_workspace_log(model_name, "theta_error_log", "theta_error_log", [500, 440, 615, 470]);
add_workspace_log(model_name, "position_integral_log", "position_integral_log", [500, 485, 640, 515]);
add_workspace_log(model_name, "theta_integral_log", "theta_integral_log", [500, 530, 635, 560]);
add_workspace_log(model_name, "kp_theta_log", "kp_theta_log", [500, 575, 615, 605]);
add_workspace_log(model_name, "ki_theta_log", "ki_theta_log", [500, 620, 615, 650]);
add_workspace_log(model_name, "kd_theta_log", "kd_theta_log", [500, 665, 615, 695]);
add_workspace_log(model_name, "u_raw_log", "u_raw_log", [505, 15, 595, 45]);
add_workspace_log(model_name, "u_log", "u_log", [610, 75, 680, 105]);
add_workspace_log(model_name, "disturbance_force_log", "disturbance_force_log", [650, 300, 785, 330]);
add_workspace_log(model_name, "disturbance_torque_log", "disturbance_torque_log", [650, 345, 785, 375]);

add_named_line(model_name, "position_reference/1", "reference_sampling/1", "position_reference");
add_named_line(model_name, "reference_sampling/1", "fuzzy_controller/2", "sampled_position_reference");
add_named_line(model_name, "reference_sampling/1", "position_reference_log/1", "sampled_position_reference");
add_named_line(model_name, "controller_reset/1", "reset_sampling/1", "controller_reset");
add_named_line(model_name, "reset_sampling/1", "fuzzy_controller/3", "sampled_controller_reset");
add_named_line(model_name, "nonlinear_plant/1", "state_sampling/1", "state");
add_named_line(model_name, "state_sampling/1", "fuzzy_controller/1", "sampled_state");
add_named_line(model_name, "fuzzy_controller/1", "actuator_saturation/1", "u_raw");
add_named_line(model_name, "fuzzy_controller/1", "u_raw_log/1", "u_raw");
add_named_line(model_name, "fuzzy_controller/2", "position_error_log/1", "position_error");
add_named_line(model_name, "fuzzy_controller/3", "theta_reference_log/1", "theta_reference");
add_named_line(model_name, "fuzzy_controller/4", "theta_error_log/1", "theta_error");
add_named_line(model_name, "fuzzy_controller/5", "position_integral_log/1", "position_integral");
add_named_line(model_name, "fuzzy_controller/6", "theta_integral_log/1", "theta_integral");
add_named_line(model_name, "fuzzy_controller/7", "kp_theta_log/1", "kp_theta");
add_named_line(model_name, "fuzzy_controller/8", "ki_theta_log/1", "ki_theta");
add_named_line(model_name, "fuzzy_controller/9", "kd_theta_log/1", "kd_theta");
add_named_line(model_name, "actuator_saturation/1", "nonlinear_plant/1", "u");
add_named_line(model_name, "actuator_saturation/1", "u_log/1", "u");
add_named_line(model_name, "disturbance_force/1", "nonlinear_plant/2", "disturbance_force");
add_named_line(model_name, "disturbance_force/1", "disturbance_force_log/1", "disturbance_force");
add_named_line(model_name, "disturbance_torque/1", "nonlinear_plant/3", "disturbance_torque");
add_named_line(model_name, "disturbance_torque/1", "disturbance_torque_log/1", "disturbance_torque");
add_named_line(model_name, "nonlinear_plant/1", "state_demux/1", "state");
add_named_line(model_name, "nonlinear_plant/1", "state/1", "state");
add_named_line(model_name, "nonlinear_plant/1", "state_log/1", "state");

model_workspace = get_param(model_name, "ModelWorkspace");
default_data = [0.0, 0.0; 8.0, 0.0];
default_reset = [0.0, 1.0; params.plant_step, 0.0; 8.0, 0.0];
assignin(model_workspace, "position_reference_data", default_data);
assignin(model_workspace, "controller_reset_data", default_reset);
assignin(model_workspace, "disturbance_force_data", default_data);
assignin(model_workspace, "disturbance_torque_data", default_data);

set_param(model_name, "SimulationCommand", "update");
save_system(model_name, model_path);
close_system(model_name, 0);
close_system(plant_model_name, 0);
clear model_cleanup plant_cleanup;
end

function script = make_controller_script(params)
lines = [ ...
    "function [u_raw, position_error, theta_reference, theta_error, position_integral, theta_integral, kp_theta, ki_theta, kd_theta] = fuzzy_controller(sampled_state, sampled_position_reference, sampled_controller_reset)"; ...
    "%#codegen"; ...
    "persistent position_integral_state theta_integral_state"; ...
    "if isempty(position_integral_state) || sampled_controller_reset ~= 0"; ...
    "    position_integral_state = 0.0;"; ...
    "    theta_integral_state = 0.0;"; ...
    "end"; ...
    string(sprintf("kp_x = %.17g;", params.kp_x)); ...
    string(sprintf("ki_x = %.17g;", params.ki_x)); ...
    string(sprintf("kd_x = %.17g;", params.kd_x)); ...
    string(sprintf("kp_theta_base = %.17g;", params.kp_theta_base)); ...
    string(sprintf("ki_theta_base = %.17g;", params.ki_theta_base)); ...
    string(sprintf("kd_theta_base = %.17g;", params.kd_theta_base)); ...
    string(sprintf("alpha_p = %.17g;", params.alpha_p)); ...
    string(sprintf("alpha_i = %.17g;", params.alpha_i)); ...
    string(sprintf("alpha_d = %.17g;", params.alpha_d)); ...
    string(sprintf("theta_error_normalizer = %.17g;", params.theta_error_normalizer)); ...
    string(sprintf("theta_rate_normalizer = %.17g;", params.theta_rate_normalizer)); ...
    string(sprintf("kp_theta_max = %.17g;", params.kp_theta_max)); ...
    string(sprintf("ki_theta_max = %.17g;", params.ki_theta_max)); ...
    string(sprintf("kd_theta_max = %.17g;", params.kd_theta_max)); ...
    string(sprintf("sample_time = %.17g;", params.sample_time)); ...
    string(sprintf("theta_reference_limit = %.17g;", params.theta_reference_limit)); ...
    string(sprintf("position_integral_limit = %.17g;", params.position_integral_limit)); ...
    string(sprintf("theta_integral_limit = %.17g;", params.theta_integral_limit)); ...
    string(sprintf("u_max = %.17g;", params.u_max)); ...
    "x = sampled_state(1);"; ...
    "x_dot = sampled_state(2);"; ...
    "theta = sampled_state(3);"; ...
    "theta_dot = sampled_state(4);"; ...
    "position_integral = position_integral_state;"; ...
    "theta_integral = theta_integral_state;"; ...
    "position_error = sampled_position_reference - x;"; ...
    "theta_reference_raw = kp_x * position_error + ki_x * position_integral - kd_x * x_dot;"; ...
    "theta_reference = min(max(theta_reference_raw, -theta_reference_limit), theta_reference_limit);"; ...
    "theta_error = theta - theta_reference;"; ...
    "[adjustments, ~] = fuzzy_pid_inference(theta_error / theta_error_normalizer, theta_dot / theta_rate_normalizer);"; ...
    "kp_theta = clamp_gain(kp_theta_base * (1.0 + alpha_p * adjustments.delta_kp), kp_theta_max);"; ...
    "ki_theta = clamp_gain(ki_theta_base * (1.0 + alpha_i * adjustments.delta_ki), ki_theta_max);"; ...
    "kd_theta = clamp_gain(kd_theta_base * (1.0 + alpha_d * adjustments.delta_kd), kd_theta_max);"; ...
    "u_raw = kp_theta * theta_error + ki_theta * theta_integral + kd_theta * theta_dot;"; ...
    "position_integral_state = min(max(position_integral + sample_time * position_error, -position_integral_limit), position_integral_limit);"; ...
    "if abs(u_raw) <= u_max || theta_error * u_raw < 0"; ...
    "    theta_integral_state = min(max(theta_integral + sample_time * theta_error, -theta_integral_limit), theta_integral_limit);"; ...
    "end"; ...
    "end"; ...
    "function gain = clamp_gain(value, gain_max)"; ...
    "gain = min(max(value, 0.0), gain_max);"; ...
    "end"];
script = strjoin(lines, newline);
end

function chart = find_chart(block_path)
root = sfroot;
chart = root.find("-isa", "Stateflow.EMChart", "Path", char(block_path));
end

function add_workspace_log(model_name, block_name, variable_name, position)
add_block("simulink/Sinks/To Workspace", model_name + "/" + block_name, ...
    "VariableName", variable_name, "SaveFormat", "Structure With Time", ...
    "Position", position);
end

function add_named_line(model_name, source, destination, signal_name)
line_handle = add_line(model_name, source, destination, "autorouting", "on");
set_param(line_handle, "Name", signal_name);
end

function close_model_if_loaded(model_name)
if bdIsLoaded(model_name)
    close_system(model_name, 0);
end
end
