function model_path = create_cascade_pid_simulink_model( ...
    plant_params, params, plant_model_path, model_path)
%CREATE_CASCADE_PID_SIMULINK_MODEL Create a fresh cascade PID model.

model_name = "twsbr_cascade_pid";
plant_model_name = "twsbr_plant";
load_system("simulink");
load_system(plant_model_path);
plant_cleanup = onCleanup(@() close_model_if_loaded(plant_model_name));
new_system(model_name);
model_cleanup = onCleanup(@() close_model_if_loaded(model_name));

set_param(model_name, ...
    "SolverType", "Variable-step", ...
    "Solver", "ode45", ...
    "RelTol", "1e-9", ...
    "AbsTol", "1e-11", ...
    "MaxStep", sprintf("%.17g", params.plant_step), ...
    "StopTime", "8.0", ...
    "ReturnWorkspaceOutputs", "on");

add_block("simulink/Sources/From Workspace", ...
    model_name + "/position_reference", ...
    "VariableName", "position_reference_data", ...
    "Interpolate", "off", ...
    "OutputAfterFinalValue", "Holding final value", ...
    "Position", [25, 45, 145, 75]);
add_block("simulink/Discrete/Zero-Order Hold", ...
    model_name + "/reference_sampling", ...
    "SampleTime", sprintf("%.17g", params.sample_time), ...
    "Position", [180, 45, 235, 75]);
add_block("simulink/Sources/From Workspace", ...
    model_name + "/controller_reset", ...
    "VariableName", "controller_reset_data", ...
    "Interpolate", "off", ...
    "OutputAfterFinalValue", "Holding final value", ...
    "Position", [25, 100, 145, 130]);
add_block("simulink/Discrete/Zero-Order Hold", ...
    model_name + "/reset_sampling", ...
    "SampleTime", sprintf("%.17g", params.sample_time), ...
    "Position", [180, 100, 235, 130]);
add_block("simulink/Discrete/Zero-Order Hold", ...
    model_name + "/state_sampling", ...
    "SampleTime", sprintf("%.17g", params.sample_time), ...
    "Position", [180, 175, 235, 220]);
add_block("simulink/User-Defined Functions/MATLAB Function", ...
    model_name + "/cascade_controller", ...
    "Position", [300, 55, 475, 235]);
add_block("simulink/Discontinuities/Saturation", ...
    model_name + "/actuator_saturation", ...
    "UpperLimit", sprintf("%.17g", params.u_max), ...
    "LowerLimit", sprintf("%.17g", -params.u_max), ...
    "Position", [535, 70, 590, 110]);
add_block(plant_model_name + "/nonlinear_plant", ...
    model_name + "/nonlinear_plant", ...
    "Position", [690, 125, 895, 280]);

plant_chart_path = model_name + "/nonlinear_plant/plant_dynamics";
controller_chart_path = model_name + "/cascade_controller";
stateflow_root = sfroot;
plant_chart = stateflow_root.find( ...
    "-isa", "Stateflow.EMChart", "Path", char(plant_chart_path));
controller_chart = stateflow_root.find( ...
    "-isa", "Stateflow.EMChart", "Path", char(controller_chart_path));
if isempty(plant_chart) || isempty(controller_chart)
    error("twsbr:simulink:function_block_not_found", ...
        "Could not configure a MATLAB Function block.");
end
plant_chart.Script = char(make_dynamics_script(plant_params));
controller_chart.Script = char(make_controller_script(params));

add_block("simulink/Sources/From Workspace", ...
    model_name + "/disturbance_force", ...
    "VariableName", "disturbance_force_data", ...
    "Interpolate", "off", ...
    "OutputAfterFinalValue", "Holding final value", ...
    "Position", [515, 190, 635, 220]);
add_block("simulink/Sources/From Workspace", ...
    model_name + "/disturbance_torque", ...
    "VariableName", "disturbance_torque_data", ...
    "Interpolate", "off", ...
    "OutputAfterFinalValue", "Holding final value", ...
    "Position", [515, 250, 635, 280]);
add_block("simulink/Signal Routing/Demux", model_name + "/state_demux", ...
    "Outputs", "4", ...
    "Position", [935, 120, 940, 285]);
add_block("simulink/Sinks/Out1", model_name + "/state", ...
    "Position", [1010, 315, 1040, 335]);

add_workspace_log(model_name, "state_log", "state_log", ...
    [925, 335, 1015, 365]);
add_workspace_log(model_name, "position_reference_log", ...
    "position_reference_log", [255, 15, 390, 45]);
add_workspace_log(model_name, "position_error_log", ...
    "position_error_log", [500, 300, 620, 330]);
add_workspace_log(model_name, "theta_reference_raw_log", ...
    "theta_reference_raw_log", [500, 345, 650, 375]);
add_workspace_log(model_name, "theta_reference_log", ...
    "theta_reference_log", [500, 390, 635, 420]);
add_workspace_log(model_name, "theta_error_log", ...
    "theta_error_log", [500, 435, 615, 465]);
add_workspace_log(model_name, "u_raw_log", "u_raw_log", ...
    [505, 15, 595, 45]);
add_workspace_log(model_name, "u_log", "u_log", ...
    [610, 75, 680, 105]);
add_workspace_log(model_name, "position_integral_log", ...
    "position_integral_log", [500, 480, 640, 510]);
add_workspace_log(model_name, "disturbance_force_log", ...
    "disturbance_force_log", [650, 300, 785, 330]);
add_workspace_log(model_name, "position_log", "position_log", ...
    [980, 60, 1070, 90]);
add_workspace_log(model_name, "position_rate_log", "position_rate_log", ...
    [980, 105, 1085, 135]);
add_workspace_log(model_name, "tilt_log", "tilt_log", ...
    [980, 150, 1070, 180]);
add_workspace_log(model_name, "angular_rate_log", "angular_rate_log", ...
    [980, 195, 1095, 225]);

add_named_line(model_name, "position_reference/1", ...
    "reference_sampling/1", "position_reference");
add_named_line(model_name, "reference_sampling/1", ...
    "cascade_controller/2", "sampled_position_reference");
add_named_line(model_name, "reference_sampling/1", ...
    "position_reference_log/1", "sampled_position_reference");
add_named_line(model_name, "controller_reset/1", ...
    "reset_sampling/1", "controller_reset");
add_named_line(model_name, "reset_sampling/1", ...
    "cascade_controller/3", "sampled_controller_reset");
add_named_line(model_name, "nonlinear_plant/1", ...
    "state_sampling/1", "state");
add_named_line(model_name, "state_sampling/1", ...
    "cascade_controller/1", "sampled_state");
add_named_line(model_name, "cascade_controller/1", ...
    "actuator_saturation/1", "u_raw");
add_named_line(model_name, "cascade_controller/1", ...
    "u_raw_log/1", "u_raw");
add_named_line(model_name, "cascade_controller/2", ...
    "position_error_log/1", "position_error");
add_named_line(model_name, "cascade_controller/3", ...
    "theta_reference_raw_log/1", "theta_reference_raw");
add_named_line(model_name, "cascade_controller/4", ...
    "theta_reference_log/1", "theta_reference");
add_named_line(model_name, "cascade_controller/5", ...
    "theta_error_log/1", "theta_error");
add_named_line(model_name, "cascade_controller/6", ...
    "position_integral_log/1", "position_integral");
add_named_line(model_name, "actuator_saturation/1", ...
    "nonlinear_plant/1", "u");
add_named_line(model_name, "actuator_saturation/1", ...
    "u_log/1", "u");
add_named_line(model_name, "disturbance_force/1", ...
    "nonlinear_plant/2", "disturbance_force");
add_named_line(model_name, "disturbance_force/1", ...
    "disturbance_force_log/1", "disturbance_force");
add_named_line(model_name, "disturbance_torque/1", ...
    "nonlinear_plant/3", "disturbance_torque");
add_named_line(model_name, "nonlinear_plant/1", ...
    "state_demux/1", "state");
add_named_line(model_name, "nonlinear_plant/1", "state/1", "state");
add_named_line(model_name, "nonlinear_plant/1", "state_log/1", "state");
add_named_line(model_name, "state_demux/1", "position_log/1", "position");
add_named_line(model_name, "state_demux/2", ...
    "position_rate_log/1", "position_rate");
add_named_line(model_name, "state_demux/3", "tilt_log/1", "tilt");
add_named_line(model_name, "state_demux/4", ...
    "angular_rate_log/1", "angular_rate");

model_workspace = get_param(model_name, "ModelWorkspace");
default_data = [0.0, 0.0; 8.0, 0.0];
default_reset = [0.0, 1.0; params.plant_step, 0.0; 8.0, 0.0];
assignin(model_workspace, "position_reference_data", default_data);
assignin(model_workspace, "controller_reset_data", default_reset);
assignin(model_workspace, "disturbance_force_data", default_data);
assignin(model_workspace, "disturbance_torque_data", default_data);

set_param(model_name, "SimulationCommand", "update");
save_system(model_name, model_path);
close_system(model_name, 0);
close_system(plant_model_name, 0);
clear model_cleanup plant_cleanup;
end

function add_workspace_log(model_name, block_name, variable_name, position)
add_block("simulink/Sinks/To Workspace", model_name + "/" + block_name, ...
    "VariableName", variable_name, ...
    "SaveFormat", "Structure With Time", ...
    "Position", position);
end

function add_named_line(model_name, source, destination, signal_name)
line_handle = add_line(model_name, source, destination, "autorouting", "on");
set_param(line_handle, "Name", signal_name);
end

function script = make_controller_script(params)
lines = [ ...
    "function [u_raw, position_error, theta_reference_raw, theta_reference, theta_error, position_integral] = cascade_controller(sampled_state, position_reference, reset)"; ...
    "%#codegen"; ...
    "persistent position_integral_state"; ...
    "if isempty(position_integral_state) || reset ~= 0"; ...
    "    position_integral_state = 0.0;"; ...
    "end"; ...
    string(sprintf("kp_x = %.17g;", params.kp_x)); ...
    string(sprintf("ki_x = %.17g;", params.ki_x)); ...
    string(sprintf("kd_x = %.17g;", params.kd_x)); ...
    string(sprintf("kp_theta = %.17g;", params.kp_theta)); ...
    string(sprintf("kd_theta = %.17g;", params.kd_theta)); ...
    string(sprintf("sample_time = %.17g;", params.sample_time)); ...
    string(sprintf("theta_reference_limit = %.17g;", params.theta_reference_limit)); ...
    string(sprintf("position_integral_limit = %.17g;", params.position_integral_limit)); ...
    "x = sampled_state(1);"; ...
    "x_dot = sampled_state(2);"; ...
    "theta = sampled_state(3);"; ...
    "theta_dot = sampled_state(4);"; ...
    "position_integral = position_integral_state;"; ...
    "position_error = position_reference - x;"; ...
    "theta_reference_raw = kp_x * position_error + ki_x * position_integral - kd_x * x_dot;"; ...
    "theta_reference = min(max(theta_reference_raw, -theta_reference_limit), theta_reference_limit);"; ...
    "theta_error = theta - theta_reference;"; ...
    "u_raw = kp_theta * theta_error + kd_theta * theta_dot;"; ...
    "position_integral_state = position_integral_state + sample_time * position_error;"; ...
    "position_integral_state = min(max(position_integral_state, -position_integral_limit), position_integral_limit);"; ...
    "end"];
script = strjoin(lines, newline);
end

function script = make_dynamics_script(params)
lines = [ ...
    "function state_dot = plant_dynamics(state, u, force_disturbance, torque_disturbance)"; ...
    "%#codegen"; ...
    string(sprintf("body_mass = %.17g;", params.body_mass)); ...
    string(sprintf("wheel_mass = %.17g;", params.wheel_mass_equiv)); ...
    string(sprintf("com_length = %.17g;", params.com_length)); ...
    string(sprintf("body_inertia = %.17g;", params.body_inertia)); ...
    string(sprintf("damping = %.17g;", params.viscous_damping)); ...
    string(sprintf("gravity = %.17g;", params.gravity)); ...
    string(sprintf("motor_gain = %.17g;", params.motor_force_gain)); ...
    "x_dot = state(2);"; ...
    "theta = state(3);"; ...
    "theta_dot = state(4);"; ...
    "force = motor_gain * u + force_disturbance;"; ...
    "mass_sum = wheel_mass + body_mass;"; ...
    "rotational_term = body_inertia + body_mass * com_length^2;"; ...
    "coupling = body_mass * com_length * cos(theta);"; ...
    "rhs_position = force - damping * x_dot + body_mass * com_length * theta_dot^2 * sin(theta);"; ...
    "rhs_angle = body_mass * gravity * com_length * sin(theta) + torque_disturbance;"; ...
    "determinant = mass_sum * rotational_term - coupling^2;"; ...
    "x_ddot = (rotational_term * rhs_position - coupling * rhs_angle) / determinant;"; ...
    "theta_ddot = (-coupling * rhs_position + mass_sum * rhs_angle) / determinant;"; ...
    "state_dot = [x_dot; x_ddot; theta_dot; theta_ddot];"; ...
    "end"];
script = strjoin(lines, newline);
end

function close_model_if_loaded(model_name)
if bdIsLoaded(model_name)
    close_system(model_name, 0);
end
end
