function model_path = create_attitude_pid_simulink_model( ...
    plant_params, pid_params, plant_model_path, model_path)
%CREATE_ATTITUDE_PID_SIMULINK_MODEL Create a fresh closed loop model.

model_name = "twsbr_attitude_pid";
plant_model_name = "twsbr_plant";
load_system("simulink");
load_system(plant_model_path);
plant_cleanup = onCleanup(@() close_model_if_loaded(plant_model_name));
new_system(model_name);
model_cleanup = onCleanup(@() close_model_if_loaded(model_name));

set_param(model_name, ...
    "SolverType", "Variable-step", ...
    "Solver", "ode45", ...
    "RelTol", "1e-9", ...
    "AbsTol", "1e-11", ...
    "MaxStep", sprintf("%.17g", pid_params.plant_step), ...
    "StopTime", "5.0", ...
    "ReturnWorkspaceOutputs", "on");

add_block("simulink/Sources/From Workspace", ...
    model_name + "/theta_reference", ...
    "VariableName", "theta_reference_data", ...
    "Interpolate", "off", ...
    "OutputAfterFinalValue", "Holding final value", ...
    "Position", [25, 70, 130, 100]);
add_block("simulink/Discrete/Zero-Order Hold", ...
    model_name + "/reference_sampling", ...
    "SampleTime", sprintf("%.17g", pid_params.sample_time), ...
    "Position", [175, 70, 230, 100]);
add_block("simulink/Discrete/Zero-Order Hold", ...
    model_name + "/state_sampling", ...
    "SampleTime", sprintf("%.17g", pid_params.sample_time), ...
    "Position", [175, 160, 230, 205]);
add_block("simulink/User-Defined Functions/MATLAB Function", ...
    model_name + "/attitude_pid", ...
    "Position", [285, 80, 445, 215]);
add_block("simulink/Discontinuities/Saturation", ...
    model_name + "/actuator_saturation", ...
    "UpperLimit", sprintf("%.17g", pid_params.u_max), ...
    "LowerLimit", sprintf("%.17g", -pid_params.u_max), ...
    "Position", [500, 105, 555, 145]);
add_block(plant_model_name + "/nonlinear_plant", ...
    model_name + "/nonlinear_plant", ...
    "Position", [650, 105, 855, 260]);

plant_chart_path = model_name + "/nonlinear_plant/plant_dynamics";
pid_chart_path = model_name + "/attitude_pid";
stateflow_root = sfroot;
plant_chart = stateflow_root.find( ...
    "-isa", "Stateflow.EMChart", "Path", char(plant_chart_path));
pid_chart = stateflow_root.find( ...
    "-isa", "Stateflow.EMChart", "Path", char(pid_chart_path));
if isempty(plant_chart) || isempty(pid_chart)
    error("twsbr:simulink:function_block_not_found", ...
        "Could not configure a MATLAB Function block.");
end
plant_chart.Script = char(make_dynamics_script(plant_params));
pid_chart.Script = char(make_pid_script(pid_params));

add_block("simulink/Sources/From Workspace", ...
    model_name + "/force_disturbance", ...
    "VariableName", "force_disturbance_data", ...
    "Interpolate", "off", ...
    "OutputAfterFinalValue", "Holding final value", ...
    "Position", [480, 215, 600, 245]);
add_block("simulink/Sources/From Workspace", ...
    model_name + "/torque_disturbance", ...
    "VariableName", "torque_disturbance_data", ...
    "Interpolate", "off", ...
    "OutputAfterFinalValue", "Holding final value", ...
    "Position", [480, 275, 600, 305]);
add_block("simulink/Sinks/Out1", model_name + "/state", ...
    "Position", [930, 125, 960, 145]);

add_workspace_log(model_name, "state_log", "state_log", [905, 180, 995, 210]);
add_workspace_log(model_name, "u_raw_log", "u_raw_log", [500, 25, 590, 55]);
add_workspace_log(model_name, "u_log", "u_log", [575, 115, 635, 145]);
add_workspace_log(model_name, "theta_error_log", ...
    "theta_error_log", [500, 160, 615, 190]);
add_workspace_log(model_name, "integral_error_log", ...
    "integral_error_log", [285, 245, 410, 275]);
add_workspace_log(model_name, "theta_reference_log", ...
    "theta_reference_log", [175, 25, 305, 55]);

add_named_line(model_name, "theta_reference/1", ...
    "reference_sampling/1", "theta_reference");
add_named_line(model_name, "reference_sampling/1", ...
    "attitude_pid/2", "sampled_reference");
add_named_line(model_name, "reference_sampling/1", ...
    "theta_reference_log/1", "sampled_reference");
add_named_line(model_name, "nonlinear_plant/1", ...
    "state_sampling/1", "state");
add_named_line(model_name, "state_sampling/1", ...
    "attitude_pid/1", "sampled_state");
add_named_line(model_name, "attitude_pid/1", ...
    "actuator_saturation/1", "u_raw");
add_named_line(model_name, "attitude_pid/1", ...
    "u_raw_log/1", "u_raw");
add_named_line(model_name, "attitude_pid/2", ...
    "theta_error_log/1", "theta_error");
add_named_line(model_name, "attitude_pid/3", ...
    "integral_error_log/1", "integral_error");
add_named_line(model_name, "actuator_saturation/1", ...
    "nonlinear_plant/1", "u");
add_named_line(model_name, "actuator_saturation/1", ...
    "u_log/1", "u");
add_named_line(model_name, "force_disturbance/1", ...
    "nonlinear_plant/2", "force_disturbance");
add_named_line(model_name, "torque_disturbance/1", ...
    "nonlinear_plant/3", "torque_disturbance");
add_named_line(model_name, "nonlinear_plant/1", ...
    "state/1", "state");
add_named_line(model_name, "nonlinear_plant/1", ...
    "state_log/1", "state");

model_workspace = get_param(model_name, "ModelWorkspace");
default_data = [0.0, 0.0; 5.0, 0.0];
assignin(model_workspace, "theta_reference_data", default_data);
assignin(model_workspace, "force_disturbance_data", default_data);
assignin(model_workspace, "torque_disturbance_data", default_data);

set_param(model_name, "SimulationCommand", "update");
save_system(model_name, model_path);
close_system(model_name, 0);
close_system(plant_model_name, 0);
clear model_cleanup plant_cleanup;
end

function add_workspace_log(model_name, block_name, variable_name, position)
add_block("simulink/Sinks/To Workspace", model_name + "/" + block_name, ...
    "VariableName", variable_name, ...
    "SaveFormat", "Structure With Time", ...
    "Position", position);
end

function add_named_line(model_name, source, destination, signal_name)
line_handle = add_line(model_name, source, destination, "autorouting", "on");
set_param(line_handle, "Name", signal_name);
end

function script = make_pid_script(pid_params)
lines = [ ...
    "function [u_raw, theta_error, integral_error] = attitude_pid(sampled_state, theta_reference)"; ...
    "%#codegen"; ...
    "persistent integral_state"; ...
    "if isempty(integral_state)"; ...
    "    integral_state = 0.0;"; ...
    "end"; ...
    string(sprintf("kp = %.17g;", pid_params.kp)); ...
    string(sprintf("ki = %.17g;", pid_params.ki)); ...
    string(sprintf("kd = %.17g;", pid_params.kd)); ...
    string(sprintf("sample_time = %.17g;", pid_params.sample_time)); ...
    string(sprintf("integral_limit = %.17g;", pid_params.integral_limit)); ...
    string(sprintf("u_max = %.17g;", pid_params.u_max)); ...
    "theta = sampled_state(3);"; ...
    "theta_dot = sampled_state(4);"; ...
    "theta_error = theta - theta_reference;"; ...
    "u_raw = kp * theta_error + ki * integral_state + kd * theta_dot;"; ...
    "saturated = abs(u_raw) > u_max + 1.0e-12;"; ...
    "if ~saturated || theta_error * u_raw < 0.0"; ...
    "    integral_state = integral_state + sample_time * theta_error;"; ...
    "end"; ...
    "integral_state = min(max(integral_state, -integral_limit), integral_limit);"; ...
    "integral_error = integral_state;"; ...
    "end"];
script = strjoin(lines, newline);
end

function script = make_dynamics_script(params)
lines = [ ...
    "function state_dot = plant_dynamics(state, u, force_disturbance, torque_disturbance)"; ...
    "%#codegen"; ...
    string(sprintf("body_mass = %.17g;", params.body_mass)); ...
    string(sprintf("wheel_mass = %.17g;", params.wheel_mass_equiv)); ...
    string(sprintf("com_length = %.17g;", params.com_length)); ...
    string(sprintf("body_inertia = %.17g;", params.body_inertia)); ...
    string(sprintf("damping = %.17g;", params.viscous_damping)); ...
    string(sprintf("gravity = %.17g;", params.gravity)); ...
    string(sprintf("motor_gain = %.17g;", params.motor_force_gain)); ...
    "x_dot = state(2);"; ...
    "theta = state(3);"; ...
    "theta_dot = state(4);"; ...
    "force = motor_gain * u + force_disturbance;"; ...
    "mass_sum = wheel_mass + body_mass;"; ...
    "rotational_term = body_inertia + body_mass * com_length^2;"; ...
    "coupling = body_mass * com_length * cos(theta);"; ...
    "rhs_position = force - damping * x_dot + body_mass * com_length * theta_dot^2 * sin(theta);"; ...
    "rhs_angle = body_mass * gravity * com_length * sin(theta) + torque_disturbance;"; ...
    "determinant = mass_sum * rotational_term - coupling^2;"; ...
    "x_ddot = (rotational_term * rhs_position - coupling * rhs_angle) / determinant;"; ...
    "theta_ddot = (-coupling * rhs_position + mass_sum * rhs_angle) / determinant;"; ...
    "state_dot = [x_dot; x_ddot; theta_dot; theta_ddot];"; ...
    "end"];
script = strjoin(lines, newline);
end

function close_model_if_loaded(model_name)
if bdIsLoaded(model_name)
    close_system(model_name, 0);
end
end
