function model_path = create_lqr_simulink_model( ...
    plant_params, params, plant_model_path, model_path)
%CREATE_LQR_SIMULINK_MODEL Create a fresh sampled full-state LQR model.

model_name = "twsbr_lqr";
plant_model_name = "twsbr_plant";
load_system("simulink");
load_system(plant_model_path);
plant_cleanup = onCleanup(@() close_model_if_loaded(plant_model_name));
new_system(model_name);
model_cleanup = onCleanup(@() close_model_if_loaded(model_name));

set_param(model_name, ...
    "SolverType", "Variable-step", ...
    "Solver", "ode45", ...
    "RelTol", "1e-9", ...
    "AbsTol", "1e-11", ...
    "MaxStep", sprintf("%.17g", params.plant_step), ...
    "StopTime", "8.0", ...
    "ReturnWorkspaceOutputs", "on");

add_block("simulink/Sources/From Workspace", ...
    model_name + "/position_reference", ...
    "VariableName", "position_reference_data", ...
    "Interpolate", "off", ...
    "OutputAfterFinalValue", "Holding final value", ...
    "Position", [25, 50, 145, 80]);
add_block("simulink/Discrete/Zero-Order Hold", ...
    model_name + "/reference_sampling", ...
    "SampleTime", sprintf("%.17g", params.sample_time), ...
    "Position", [185, 50, 245, 80]);
add_block("simulink/Sources/Constant", ...
    model_name + "/reference_position_rate", ...
    "Value", "0.0", "Position", [285, 90, 335, 120]);
add_block("simulink/Sources/Constant", model_name + "/reference_tilt", ...
    "Value", "0.0", "Position", [285, 135, 335, 165]);
add_block("simulink/Sources/Constant", ...
    model_name + "/reference_angular_rate", ...
    "Value", "0.0", "Position", [285, 180, 335, 210]);
add_block("simulink/Signal Routing/Mux", model_name + "/reference_state", ...
    "Inputs", "4", "Position", [390, 65, 395, 215]);
add_block("simulink/Discrete/Zero-Order Hold", ...
    model_name + "/state_sampling", ...
    "SampleTime", sprintf("%.17g", params.sample_time), ...
    "Position", [600, 220, 660, 250]);
add_block("simulink/Math Operations/Sum", model_name + "/state_error", ...
    "Inputs", "+-", "Position", [710, 105, 735, 145]);
add_block("simulink/Math Operations/Gain", model_name + "/lqr_gain", ...
    "Gain", mat2str(-params.gain, 17), ...
    "Multiplication", "Matrix(K*u)", "Position", [780, 105, 875, 145]);
add_block("simulink/Discontinuities/Saturation", ...
    model_name + "/actuator_saturation", ...
    "UpperLimit", sprintf("%.17g", plant_params.u_max), ...
    "LowerLimit", sprintf("%.17g", -plant_params.u_max), ...
    "Position", [930, 105, 985, 145]);
add_block(plant_model_name + "/nonlinear_plant", ...
    model_name + "/nonlinear_plant", "Position", [1080, 175, 1285, 330]);
add_block("simulink/Sources/From Workspace", ...
    model_name + "/disturbance_force", ...
    "VariableName", "disturbance_force_data", ...
    "Interpolate", "off", ...
    "OutputAfterFinalValue", "Holding final value", ...
    "Position", [930, 225, 1050, 255]);
add_block("simulink/Sources/From Workspace", ...
    model_name + "/disturbance_torque", ...
    "VariableName", "disturbance_torque_data", ...
    "Interpolate", "off", ...
    "OutputAfterFinalValue", "Holding final value", ...
    "Position", [930, 280, 1050, 310]);
add_block("simulink/Sinks/Out1", model_name + "/state", ...
    "Position", [1385, 195, 1415, 215]);

add_workspace_log(model_name, "position_reference_log", ...
    "position_reference_log", [430, 25, 570, 55]);
add_workspace_log(model_name, "u_raw_log", "u_raw_log", ...
    [790, 45, 880, 75]);
add_workspace_log(model_name, "u_log", "u_log", [995, 105, 1060, 135]);
add_workspace_log(model_name, "disturbance_force_log", ...
    "disturbance_force_log", [930, 345, 1065, 375]);
add_workspace_log(model_name, "disturbance_torque_log", ...
    "disturbance_torque_log", [930, 390, 1070, 420]);
add_workspace_log(model_name, "state_log", "state_log", ...
    [1325, 260, 1415, 290]);

add_named_line(model_name, "position_reference/1", ...
    "reference_sampling/1", "position_reference");
add_named_line(model_name, "reference_sampling/1", ...
    "reference_state/1", "sampled_position_reference");
add_named_line(model_name, "reference_sampling/1", ...
    "position_reference_log/1", "sampled_position_reference");
add_named_line(model_name, "reference_position_rate/1", ...
    "reference_state/2", "reference_position_rate");
add_named_line(model_name, "reference_tilt/1", ...
    "reference_state/3", "reference_tilt");
add_named_line(model_name, "reference_angular_rate/1", ...
    "reference_state/4", "reference_angular_rate");
add_named_line(model_name, "reference_state/1", "state_error/2", ...
    "sampled_reference_state");
add_named_line(model_name, "nonlinear_plant/1", "state_sampling/1", ...
    "state");
add_named_line(model_name, "state_sampling/1", "state_error/1", ...
    "sampled_state");
add_named_line(model_name, "state_error/1", "lqr_gain/1", "state_error");
add_named_line(model_name, "lqr_gain/1", "actuator_saturation/1", "u_raw");
add_named_line(model_name, "lqr_gain/1", "u_raw_log/1", "u_raw");
add_named_line(model_name, "actuator_saturation/1", "nonlinear_plant/1", "u");
add_named_line(model_name, "actuator_saturation/1", "u_log/1", "u");
add_named_line(model_name, "disturbance_force/1", "nonlinear_plant/2", ...
    "disturbance_force");
add_named_line(model_name, "disturbance_force/1", ...
    "disturbance_force_log/1", "disturbance_force");
add_named_line(model_name, "disturbance_torque/1", "nonlinear_plant/3", ...
    "disturbance_torque");
add_named_line(model_name, "disturbance_torque/1", ...
    "disturbance_torque_log/1", "disturbance_torque");
add_named_line(model_name, "nonlinear_plant/1", "state/1", "state");
add_named_line(model_name, "nonlinear_plant/1", "state_log/1", "state");

model_workspace = get_param(model_name, "ModelWorkspace");
default_data = [0.0, 0.0; 8.0, 0.0];
assignin(model_workspace, "position_reference_data", default_data);
assignin(model_workspace, "disturbance_force_data", default_data);
assignin(model_workspace, "disturbance_torque_data", default_data);

set_param(model_name, "SimulationCommand", "update");
save_system(model_name, model_path);
close_system(model_name, 0);
close_system(plant_model_name, 0);
clear model_cleanup plant_cleanup;
end

function add_workspace_log(model_name, block_name, variable_name, position)
add_block("simulink/Sinks/To Workspace", model_name + "/" + block_name, ...
    "VariableName", variable_name, ...
    "SaveFormat", "Structure With Time", ...
    "Position", position);
end

function add_named_line(model_name, source, destination, signal_name)
line_handle = add_line(model_name, source, destination, "autorouting", "on");
set_param(line_handle, "Name", signal_name);
end

function close_model_if_loaded(model_name)
if bdIsLoaded(model_name)
    close_system(model_name, 0);
end
end
