function model_path = create_twsbr_simulink_model(params, model_path)
%CREATE_TWSBR_SIMULINK_MODEL Create a fresh TWSBR Simulink model.

model_name = "twsbr_plant";
load_system("simulink");
new_system(model_name);
cleanup = onCleanup(@() close_model_on_error(model_name));

set_param(model_name, ...
    "SolverType", "Variable-step", ...
    "Solver", "ode45", ...
    "RelTol", "1e-9", ...
    "AbsTol", "1e-11", ...
    "MaxStep", "0.01", ...
    "StopTime", "2.0", ...
    "ReturnWorkspaceOutputs", "on");

add_block("simulink/Sources/Constant", model_name + "/u", ...
    "Value", "0.0", ...
    "Position", [30, 55, 80, 85]);
add_block("simulink/Sources/Constant", ...
    model_name + "/force_disturbance", ...
    "Value", "0.0", ...
    "Position", [30, 125, 80, 155]);
add_block("simulink/Sources/Constant", ...
    model_name + "/torque_disturbance", ...
    "Value", "0.0", ...
    "Position", [30, 195, 80, 225]);

plant_path = model_name + "/nonlinear_plant";
add_block("simulink/Ports & Subsystems/Subsystem", plant_path, ...
    "Position", [170, 70, 390, 215]);
Simulink.SubSystem.deleteContents(plant_path);
add_block("simulink/Sinks/Out1", model_name + "/state", ...
    "Position", [520, 105, 550, 125]);
add_block("simulink/Sinks/To Workspace", model_name + "/state_log", ...
    "VariableName", "state_log", ...
    "SaveFormat", "Structure With Time", ...
    "Position", [500, 165, 590, 195]);

add_block("simulink/Ports & Subsystems/In1", plant_path + "/u", ...
    "Port", "1", ...
    "Position", [25, 55, 55, 75]);
add_block("simulink/Ports & Subsystems/In1", ...
    plant_path + "/force_disturbance", ...
    "Port", "2", ...
    "Position", [25, 110, 55, 130]);
add_block("simulink/Ports & Subsystems/In1", ...
    plant_path + "/torque_disturbance", ...
    "Port", "3", ...
    "Position", [25, 165, 55, 185]);
add_block("simulink/Continuous/Integrator", ...
    plant_path + "/state_integrator", ...
    "InitialCondition", "[0;0;0;0]", ...
    "Position", [310, 65, 345, 105]);
add_block("simulink/User-Defined Functions/MATLAB Function", ...
    plant_path + "/plant_dynamics", ...
    "Position", [125, 45, 245, 185]);
add_block("simulink/Ports & Subsystems/Out1", plant_path + "/state", ...
    "Port", "1", ...
    "Position", [405, 75, 435, 95]);

function_path = plant_path + "/plant_dynamics";
stateflow_root = sfroot;
chart = stateflow_root.find( ...
    "-isa", "Stateflow.EMChart", "Path", char(function_path));
if isempty(chart)
    error("twsbr:simulink:function_block_not_found", ...
        "Could not configure the plant dynamics block.");
end
chart.Script = char(make_dynamics_script(params));

add_named_line(plant_path, "state_integrator/1", ...
    "plant_dynamics/1", "state");
add_named_line(plant_path, "u/1", "plant_dynamics/2", "u");
add_named_line(plant_path, "force_disturbance/1", ...
    "plant_dynamics/3", "force_disturbance");
add_named_line(plant_path, "torque_disturbance/1", ...
    "plant_dynamics/4", "torque_disturbance");
add_named_line(plant_path, "plant_dynamics/1", ...
    "state_integrator/1", "state_dot");
add_named_line(plant_path, "state_integrator/1", ...
    "state/1", "state");

add_named_line(model_name, "u/1", "nonlinear_plant/1", "u");
add_named_line(model_name, "force_disturbance/1", ...
    "nonlinear_plant/2", "force_disturbance");
add_named_line(model_name, "torque_disturbance/1", ...
    "nonlinear_plant/3", "torque_disturbance");
add_named_line(model_name, "nonlinear_plant/1", "state/1", "state");
add_named_line(model_name, "nonlinear_plant/1", ...
    "state_log/1", "state");

set_param(model_name, "SimulationCommand", "update");
save_system(model_name, model_path);
close_system(model_name, 0);
clear cleanup;
end


function add_named_line(model_name, source, destination, signal_name)
line_handle = add_line(model_name, source, destination, "autorouting", "on");
set_param(line_handle, "Name", signal_name);
end

function script = make_dynamics_script(params)
lines = [ ...
    "function state_dot = plant_dynamics(state, u, force_disturbance, torque_disturbance)"; ...
    "%#codegen"; ...
    string(sprintf("body_mass = %.17g;", params.body_mass)); ...
    string(sprintf("wheel_mass = %.17g;", params.wheel_mass_equiv)); ...
    string(sprintf("com_length = %.17g;", params.com_length)); ...
    string(sprintf("body_inertia = %.17g;", params.body_inertia)); ...
    string(sprintf("damping = %.17g;", params.viscous_damping)); ...
    string(sprintf("gravity = %.17g;", params.gravity)); ...
    string(sprintf("motor_gain = %.17g;", params.motor_force_gain)); ...
    "x_dot = state(2);"; ...
    "theta = state(3);"; ...
    "theta_dot = state(4);"; ...
    "force = motor_gain * u + force_disturbance;"; ...
    "mass_sum = wheel_mass + body_mass;"; ...
    "rotational_term = body_inertia + body_mass * com_length^2;"; ...
    "coupling = body_mass * com_length * cos(theta);"; ...
    "rhs_position = force - damping * x_dot + body_mass * com_length * theta_dot^2 * sin(theta);"; ...
    "rhs_angle = body_mass * gravity * com_length * sin(theta) + torque_disturbance;"; ...
    "determinant = mass_sum * rotational_term - coupling^2;"; ...
    "x_ddot = (rotational_term * rhs_position - coupling * rhs_angle) / determinant;"; ...
    "theta_ddot = (-coupling * rhs_position + mass_sum * rhs_angle) / determinant;"; ...
    "state_dot = [x_dot; x_ddot; theta_dot; theta_ddot];"; ...
    "end"];
script = strjoin(lines, newline);
end

function close_model_on_error(model_name)
if bdIsLoaded(model_name)
    close_system(model_name, 0);
end
end
