function controller = controller_after_actuation(controller, u_raw, applied_u)
%CONTROLLER_AFTER_ACTUATION Commit state after actuator saturation is verified.

validate_finite_scalar(u_raw, "Raw control");
validate_finite_scalar(applied_u, "Applied control");
if isempty(controller.pending_state)
    error("twsbr:controller:invalid_state", ...
        "Controller has no pending state to commit.");
end

switch controller.name
    case {"ATTITUDE_PID", "CASCADE_PID"}
        validate_finite_scalar(controller.pending_legacy_u, ...
            "Pending legacy control");
        if abs(applied_u - controller.pending_legacy_u) > 1e-12
            error("twsbr:controller:legacy_saturation_mismatch", ...
                "Common and legacy actuator saturation differ.");
        end
    case "LQR"
        if ~isstruct(controller.pending_state) || ...
                ~isscalar(controller.pending_state) || ...
                ~isempty(fieldnames(controller.pending_state)) || ...
                ~isempty(controller.pending_legacy_u)
            error("twsbr:controller:invalid_state", ...
                "LQR pending state must be an empty scalar structure.");
        end
    case "LQI"
        if ~isstruct(controller.pending_state) || ...
                ~isscalar(controller.pending_state) || ...
                ~isequal(fieldnames(controller.pending_state), ...
                {"position_integral"}) || ...
                ~isnumeric(controller.pending_state.position_integral) || ...
                ~isreal(controller.pending_state.position_integral) || ...
                ~isscalar(controller.pending_state.position_integral) || ...
                ~isfinite(controller.pending_state.position_integral) || ...
                ~isfield(controller, "params") || ...
                ~isstruct(controller.params) || ...
                ~isscalar(controller.params) || ...
                ~isfield(controller.params, "position_integral_limit") || ...
                ~isnumeric(controller.params.position_integral_limit) || ...
                ~isreal(controller.params.position_integral_limit) || ...
                ~isscalar(controller.params.position_integral_limit) || ...
                ~isfinite(controller.params.position_integral_limit) || ...
                controller.params.position_integral_limit <= 0 || ...
                abs(controller.pending_state.position_integral) > ...
                controller.params.position_integral_limit || ...
                ~isempty(controller.pending_legacy_u)
            error("twsbr:controller:invalid_state", ...
                "LQI pending state must contain one bounded position integral.");
        end
    otherwise
        error("twsbr:controller:unsupported_name", ...
            "Controller is not implemented in this phase: %s", ...
            controller.name);
end

controller.state = controller.pending_state;
controller.pending_state = [];
controller.pending_legacy_u = [];
end

function validate_finite_scalar(value, value_name)
if ~isnumeric(value) || ~isreal(value) || ~isscalar(value) || ~isfinite(value)
    error("twsbr:controller:invalid_input", ...
        "%s must be a finite real numeric scalar.", value_name);
end
end
