function controller = create_controller(controller_name, vector, plant_params, config)
%CREATE_CONTROLLER Build a common controller from a bounded parameter vector.

name = upper(string(controller_name));
if ~isscalar(name) || ...
        ~ismember(name, ["ATTITUDE_PID", "CASCADE_PID", ...
        "FUZZY_PID", "LQR", "LQI"])
    error("twsbr:controller:unsupported_name", ...
        "Controller is not implemented in this phase: %s", string(controller_name));
end

controller = struct( ...
    "name", name, ...
    "params", decode_controller_vector(name, vector, plant_params, config), ...
    "state", [], ...
    "pending_state", [], ...
    "pending_legacy_u", []);
end
