function params = decode_controller_vector(controller_name, vector, plant_params, config)
%DECODE_CONTROLLER_VECTOR Decode a bounded controller parameter vector.

space = controller_parameter_space(controller_name);
validate_vector(vector, space);
if space.name == "FUZZY_PID"
    params = decode_fuzzy_pid(vector(:).', plant_params, config);
    return
end
gains = 10 .^ vector(:).';

switch space.name
    case "ATTITUDE_PID"
        params = attitude_pid_params(struct( ...
            "kp", gains(1), "ki", gains(2), "kd", gains(3), ...
            "sample_time", config.sample_time, ...
            "plant_step", config.plant_step), plant_params);
    case "CASCADE_PID"
        params = cascade_pid_params(struct( ...
            "kp_x", gains(1), "ki_x", gains(2), "kd_x", gains(3), ...
            "kp_theta", gains(4), "kd_theta", gains(5), ...
            "sample_time", config.sample_time, ...
            "plant_step", config.plant_step, ...
            "theta_reference_limit", config.theta_reference_limit), ...
            plant_params);
    case "LQR"
        params = decode_lqr(gains, plant_params, config);
    case "LQI"
        params = decode_lqi(gains, plant_params, config);
    otherwise
        error("twsbr:controller:unsupported_name", ...
            "Controller is not implemented in this phase: %s", controller_name);
end
end

function params = decode_fuzzy_pid(vector, plant_params, config)
gain_values = 10 .^ vector(1:6);
alpha_values = vector(7:9);
required_config_fields = {'sample_time', 'theta_reference_limit', ...
    'position_integral_limit'};
if ~isstruct(config) || ~isscalar(config) || ...
        ~all(isfield(config, required_config_fields)) || ...
        ~is_positive_finite_scalar(config.sample_time) || ...
        ~is_positive_finite_scalar(config.theta_reference_limit) || ...
        ~is_positive_finite_scalar(config.position_integral_limit) || ...
        ~isstruct(plant_params) || ~isscalar(plant_params) || ...
        ~isfield(plant_params, "u_max") || ...
        ~is_positive_finite_scalar(plant_params.u_max)
    error("twsbr:fuzzy_pid:invalid_input", ...
        "Fuzzy PID configuration and actuator limit must be positive and finite.");
end

params = struct( ...
    "kp_x", gain_values(1), ...
    "ki_x", gain_values(2), ...
    "kd_x", gain_values(3), ...
    "kp_theta_base", gain_values(4), ...
    "ki_theta_base", gain_values(5), ...
    "kd_theta_base", gain_values(6), ...
    "alpha_p", alpha_values(1), ...
    "alpha_i", alpha_values(2), ...
    "alpha_d", alpha_values(3), ...
    "theta_error_normalizer", deg2rad(12), ...
    "theta_rate_normalizer", deg2rad(120), ...
    "kp_theta_max", 4 * gain_values(4), ...
    "ki_theta_max", 4 * gain_values(5), ...
    "kd_theta_max", 4 * gain_values(6), ...
    "sample_time", config.sample_time, ...
    "theta_reference_limit", config.theta_reference_limit, ...
    "position_integral_limit", config.position_integral_limit, ...
    "theta_integral_limit", config.position_integral_limit, ...
    "u_max", plant_params.u_max);
end

function params = decode_lqi(weights, plant_params, config)
[ad, bd] = twsbr_discrete_model(plant_params, config.sample_time);
[a_aug, b_aug] = twsbr_augmented_lqi_model(ad, bd, config.sample_time);
q_aug_diag = weights(1:5);
r_value = weights(6);

try
    [gain_aug, ~, poles] = dlqr( ...
        a_aug, b_aug, diag(q_aug_diag), r_value);
catch cause
    if strcmp(cause.identifier, "Control:design:lqr2")
        exception = MException("twsbr:lqi:nonstabilizing_solution", ...
            "The LQI candidate does not have a stabilizing discrete solution.");
        exception = addCause(exception, cause);
        throw(exception);
    end
    rethrow(cause);
end

if ~isnumeric(gain_aug) || ~isreal(gain_aug) || ...
        ~isequal(size(gain_aug), [1, 5]) || ...
        any(~isfinite(gain_aug), "all") || ~isnumeric(poles) || ...
        numel(poles) ~= 5 || any(~isfinite(poles), "all") || ...
        any(abs(poles) >= 1)
    error("twsbr:lqi:nonstabilizing_solution", ...
        "The LQI candidate does not have a stabilizing discrete solution.");
end
if ~isnumeric(config.position_integral_limit) || ...
        ~isreal(config.position_integral_limit) || ...
        ~isscalar(config.position_integral_limit) || ...
        ~isfinite(config.position_integral_limit) || ...
        config.position_integral_limit <= 0
    error("twsbr:lqi:invalid_input", ...
        "position_integral_limit must be a positive finite real scalar.");
end

params = struct( ...
    "q_aug_diag", q_aug_diag, ...
    "r_value", r_value, ...
    "state_gain", gain_aug(1:4), ...
    "integral_gain", gain_aug(5), ...
    "closed_loop_eigenvalues", poles, ...
    "sample_time", config.sample_time, ...
    "position_integral_limit", config.position_integral_limit);
end

function params = decode_lqr(weights, plant_params, config)
[ad, bd] = twsbr_discrete_model(plant_params, config.sample_time);
q_diag = weights(1:4);
r_value = weights(5);

try
    [gain, ~, poles] = dlqr(ad, bd, diag(q_diag), r_value);
catch cause
    if strcmp(cause.identifier, "Control:design:lqr2")
        exception = MException("twsbr:lqr:nonstabilizing_solution", ...
            "The LQR candidate does not have a stabilizing discrete solution.");
        exception = addCause(exception, cause);
        throw(exception);
    end
    rethrow(cause);
end

if ~isnumeric(gain) || ~isreal(gain) || ~isequal(size(gain), [1, 4]) || ...
        any(~isfinite(gain), "all") || ~isnumeric(poles) || ...
        numel(poles) ~= 4 || any(~isfinite(poles), "all") || ...
        any(abs(poles) >= 1)
    error("twsbr:lqr:nonstabilizing_solution", ...
        "The LQR candidate does not have a stabilizing discrete solution.");
end

params = struct( ...
    "q_diag", q_diag, ...
    "r_value", r_value, ...
    "gain", gain, ...
    "closed_loop_eigenvalues", poles, ...
    "sample_time", config.sample_time);
end

function validate_vector(vector, space)
if ~isnumeric(vector) || ~isreal(vector) || ~isvector(vector) || ...
        numel(vector) ~= space.dimension || any(~isfinite(vector(:))) || ...
        any(vector(:).' < space.lower_bounds) || ...
        any(vector(:).' > space.upper_bounds)
    error("twsbr:controller:invalid_vector", ...
        "Controller vector must be a real finite vector within the parameter bounds.");
end
end

function valid = is_positive_finite_scalar(value)
valid = isnumeric(value) && isreal(value) && isscalar(value) && ...
    isfinite(value) && value > 0;
end
