function params = decode_controller_vector(controller_name, vector, plant_params, config)
%DECODE_CONTROLLER_VECTOR Decode a bounded log10 gain vector.

space = controller_parameter_space(controller_name);
validate_vector(vector, space);
gains = 10 .^ vector(:).';

switch space.name
    case "ATTITUDE_PID"
        params = attitude_pid_params(struct( ...
            "kp", gains(1), "ki", gains(2), "kd", gains(3), ...
            "sample_time", config.sample_time, ...
            "plant_step", config.plant_step), plant_params);
    case "CASCADE_PID"
        params = cascade_pid_params(struct( ...
            "kp_x", gains(1), "ki_x", gains(2), "kd_x", gains(3), ...
            "kp_theta", gains(4), "kd_theta", gains(5), ...
            "sample_time", config.sample_time, ...
            "plant_step", config.plant_step, ...
            "theta_reference_limit", config.theta_reference_limit), ...
            plant_params);
    otherwise
        error("twsbr:controller:unsupported_name", ...
            "Controller is not implemented in this phase: %s", controller_name);
end
end

function validate_vector(vector, space)
if ~isnumeric(vector) || ~isreal(vector) || ~isvector(vector) || ...
        numel(vector) ~= space.dimension || any(~isfinite(vector(:))) || ...
        any(vector(:).' < space.lower_bounds) || ...
        any(vector(:).' > space.upper_bounds)
    error("twsbr:controller:invalid_vector", ...
        "Controller vector must be a real finite vector within the parameter bounds.");
end
end
