function params = decode_controller_vector(controller_name, vector, plant_params, config)
%DECODE_CONTROLLER_VECTOR Decode a bounded log10 gain vector.

space = controller_parameter_space(controller_name);
validate_vector(vector, space);
gains = 10 .^ vector(:).';

switch space.name
    case "ATTITUDE_PID"
        params = attitude_pid_params(struct( ...
            "kp", gains(1), "ki", gains(2), "kd", gains(3), ...
            "sample_time", config.sample_time, ...
            "plant_step", config.plant_step), plant_params);
    case "CASCADE_PID"
        params = cascade_pid_params(struct( ...
            "kp_x", gains(1), "ki_x", gains(2), "kd_x", gains(3), ...
            "kp_theta", gains(4), "kd_theta", gains(5), ...
            "sample_time", config.sample_time, ...
            "plant_step", config.plant_step, ...
            "theta_reference_limit", config.theta_reference_limit), ...
            plant_params);
    case "LQR"
        params = decode_lqr(gains, plant_params, config);
    otherwise
        error("twsbr:controller:unsupported_name", ...
            "Controller is not implemented in this phase: %s", controller_name);
end
end

function params = decode_lqr(weights, plant_params, config)
[ad, bd] = twsbr_discrete_model(plant_params, config.sample_time);
q_diag = weights(1:4);
r_value = weights(5);

try
    [gain, ~, poles] = dlqr(ad, bd, diag(q_diag), r_value);
catch cause
    if strcmp(cause.identifier, "Control:design:lqr2")
        exception = MException("twsbr:lqr:nonstabilizing_solution", ...
            "The LQR candidate does not have a stabilizing discrete solution.");
        exception = addCause(exception, cause);
        throw(exception);
    end
    rethrow(cause);
end

if ~isnumeric(gain) || ~isreal(gain) || ~isequal(size(gain), [1, 4]) || ...
        any(~isfinite(gain), "all") || ~isnumeric(poles) || ...
        numel(poles) ~= 4 || any(~isfinite(poles), "all") || ...
        any(abs(poles) >= 1)
    error("twsbr:lqr:nonstabilizing_solution", ...
        "The LQR candidate does not have a stabilizing discrete solution.");
end

params = struct( ...
    "q_diag", q_diag, ...
    "r_value", r_value, ...
    "gain", gain, ...
    "closed_loop_eigenvalues", poles, ...
    "sample_time", config.sample_time);
end

function validate_vector(vector, space)
if ~isnumeric(vector) || ~isreal(vector) || ~isvector(vector) || ...
        numel(vector) ~= space.dimension || any(~isfinite(vector(:))) || ...
        any(vector(:).' < space.lower_bounds) || ...
        any(vector(:).' > space.upper_bounds)
    error("twsbr:controller:invalid_vector", ...
        "Controller vector must be a real finite vector within the parameter bounds.");
end
end
