function rules = fuzzy_pid_rule_base()
%FUZZY_PID_RULE_BASE Return the fixed seven-label singleton rule matrices.

indices = -3:3;
[error_index, rate_index] = ndgrid(indices, indices);
delta_kp = min(3, round( ...
    (abs(error_index) + abs(rate_index)) / 2));
delta_ki = max(-3, min(3, ...
    3 - abs(error_index) - abs(rate_index)));
delta_kd = max(-3, min(3, ...
    abs(rate_index) - abs(error_index)));

rules = struct( ...
    "delta_kp", delta_kp, ...
    "delta_ki", delta_ki, ...
    "delta_kd", delta_kd);
end
