function [control, next_state] = fuzzy_pid_step( ...
        controller_state, plant_state, x_reference, params)
%FUZZY_PID_STEP Advance the fuzzy self-tuning cascade by one sample.

validate_params(params);
validate_state(controller_state, params);
if ~isnumeric(plant_state) || ~isreal(plant_state) || ...
        ~isvector(plant_state) || numel(plant_state) ~= 4 || ...
        any(~isfinite(plant_state(:))) || ...
        ~is_finite_real_scalar(x_reference)
    invalid_input("Controller inputs must be finite real numeric values.");
end

plant_state = plant_state(:);
x = plant_state(1);
x_dot = plant_state(2);
theta = plant_state(3);
theta_dot = plant_state(4);
position_integral = controller_state.position_integral;
theta_integral = controller_state.theta_integral;

position_error = x_reference - x;
theta_reference_raw = params.kp_x * position_error ...
    + params.ki_x * position_integral - params.kd_x * x_dot;
theta_reference = min(max(theta_reference_raw, ...
    -params.theta_reference_limit), params.theta_reference_limit);
theta_error = theta - theta_reference;
error_normalized = theta_error / params.theta_error_normalizer;
rate_normalized = theta_dot / params.theta_rate_normalizer;
ensure_finite([position_error, theta_reference_raw, theta_reference, ...
    theta_error, error_normalized, rate_normalized]);

[adjustments, fuzzy_diagnostics] = fuzzy_pid_inference( ...
    error_normalized, rate_normalized);
kp_theta = bounded_gain(params.kp_theta_base, ...
    params.alpha_p, adjustments.delta_kp, params.kp_theta_max);
ki_theta = bounded_gain(params.ki_theta_base, ...
    params.alpha_i, adjustments.delta_ki, params.ki_theta_max);
kd_theta = bounded_gain(params.kd_theta_base, ...
    params.alpha_d, adjustments.delta_kd, params.kd_theta_max);
u_raw = kp_theta * theta_error ...
    + ki_theta * theta_integral + kd_theta * theta_dot;
ensure_finite([kp_theta, ki_theta, kd_theta, u_raw]);

next_position_integral = position_integral ...
    + params.sample_time * position_error;
ensure_finite(next_position_integral);
next_position_integral = min(max(next_position_integral, ...
    -params.position_integral_limit), params.position_integral_limit);

next_theta_integral = theta_integral;
if abs(u_raw) <= params.u_max || theta_error * u_raw < 0
    next_theta_integral = theta_integral ...
        + params.sample_time * theta_error;
    ensure_finite(next_theta_integral);
    next_theta_integral = min(max(next_theta_integral, ...
        -params.theta_integral_limit), params.theta_integral_limit);
end

control = struct( ...
    "u_raw", u_raw, ...
    "theta_reference", theta_reference, ...
    "theta_reference_raw", theta_reference_raw, ...
    "position_error", position_error, ...
    "theta_error", theta_error, ...
    "position_integral", position_integral, ...
    "theta_integral", theta_integral, ...
    "kp_theta", kp_theta, ...
    "ki_theta", ki_theta, ...
    "kd_theta", kd_theta, ...
    "adjustments", adjustments, ...
    "diagnostics", struct( ...
        "adjustments", adjustments, ...
        "fuzzy", fuzzy_diagnostics, ...
        "kp_theta", kp_theta, ...
        "ki_theta", ki_theta, ...
        "kd_theta", kd_theta));
next_state = struct( ...
    "position_integral", next_position_integral, ...
    "theta_integral", next_theta_integral);
end

function gain = bounded_gain(base_gain, alpha, adjustment, gain_limit)
gain = base_gain * (1.0 + alpha * adjustment);
gain = min(max(gain, 0.0), gain_limit);
end

function validate_state(controller_state, params)
if ~isstruct(controller_state) || ~isscalar(controller_state) || ...
        ~isequal(fieldnames(controller_state), ...
        {'position_integral'; 'theta_integral'}) || ...
        ~is_finite_real_scalar(controller_state.position_integral) || ...
        ~is_finite_real_scalar(controller_state.theta_integral) || ...
        abs(controller_state.position_integral) > ...
        params.position_integral_limit || ...
        abs(controller_state.theta_integral) > params.theta_integral_limit
    invalid_input("Controller state must contain two bounded integrals.");
end
end

function validate_params(params)
required_fields = { ...
    'kp_x', 'ki_x', 'kd_x', ...
    'kp_theta_base', 'ki_theta_base', 'kd_theta_base', ...
    'alpha_p', 'alpha_i', 'alpha_d', ...
    'theta_error_normalizer', 'theta_rate_normalizer', ...
    'kp_theta_max', 'ki_theta_max', 'kd_theta_max', ...
    'sample_time', 'theta_reference_limit', ...
    'position_integral_limit', 'theta_integral_limit', 'u_max'};
if ~isstruct(params) || ~isscalar(params) || ...
        ~all(isfield(params, required_fields))
    invalid_input("params must contain the complete fuzzy PID configuration.");
end

nonnegative_fields = {'kp_x', 'ki_x', 'kd_x', ...
    'kp_theta_base', 'ki_theta_base', 'kd_theta_base', ...
    'kp_theta_max', 'ki_theta_max', 'kd_theta_max'};
for index = 1:numel(nonnegative_fields)
    if ~is_nonnegative_finite_scalar(params.(nonnegative_fields{index}))
        invalid_input("Fuzzy PID gains and gain limits must be nonnegative.");
    end
end
alpha_fields = {'alpha_p', 'alpha_i', 'alpha_d'};
for index = 1:numel(alpha_fields)
    value = params.(alpha_fields{index});
    if ~is_finite_real_scalar(value) || value < 0 || value > 1.5
        invalid_input("Fuzzy PID adjustment ratios must be in [0, 1.5].");
    end
end
positive_fields = {'theta_error_normalizer', ...
    'theta_rate_normalizer', 'sample_time', ...
    'theta_reference_limit', 'position_integral_limit', ...
    'theta_integral_limit', 'u_max'};
for index = 1:numel(positive_fields)
    if ~is_positive_finite_scalar(params.(positive_fields{index}))
        invalid_input("Fuzzy PID normalizers, timing, limits, and u_max must be positive.");
    end
end
end

function ensure_finite(value)
if ~isnumeric(value) || ~isreal(value) || any(~isfinite(value(:)))
    invalid_input("Fuzzy PID calculations must remain finite and real.");
end
end

function valid = is_positive_finite_scalar(value)
valid = is_finite_real_scalar(value) && value > 0;
end

function valid = is_nonnegative_finite_scalar(value)
valid = is_finite_real_scalar(value) && value >= 0;
end

function valid = is_finite_real_scalar(value)
valid = isnumeric(value) && isreal(value) && isscalar(value) && ...
    isfinite(value);
end

function invalid_input(message)
error("twsbr:fuzzy_pid:invalid_input", "%s", message);
end
