function [control, next_state] = lqi_step( ...
        controller_state, plant_state, x_reference, params)
%LQI_STEP Calculate one command and the pending position integral.

validate_params(params);
validate_controller_state( ...
    controller_state, params.position_integral_limit);
if ~isnumeric(plant_state) || ~isreal(plant_state) || ...
        ~isvector(plant_state) || numel(plant_state) ~= 4 || ...
        any(~isfinite(plant_state(:)))
    invalid_input("plant_state must be a finite real four-state vector.");
end
validate_finite_scalar(x_reference, "x_reference");

plant_state = plant_state(:);
position_integral = controller_state.position_integral;
position_error = plant_state(1) - x_reference;
u_raw = -params.state_gain * plant_state ...
    - params.integral_gain * position_integral;
pending_integral = position_integral ...
    + params.sample_time * position_error;
if ~isfinite(position_error) || ~isreal(u_raw) || ...
        ~isscalar(u_raw) || ~isfinite(u_raw) || ...
        ~isreal(pending_integral) || ~isscalar(pending_integral) || ...
        ~isfinite(pending_integral)
    error("twsbr:controller:nonfinite_output", ...
        "LQI outputs must remain finite real numeric scalars.");
end

pending_integral = min(max(pending_integral, ...
    -params.position_integral_limit), params.position_integral_limit);
control = struct( ...
    "u_raw", u_raw, ...
    "theta_reference", 0.0, ...
    "position_error", position_error, ...
    "position_integral", position_integral, ...
    "diagnostics", struct("position_integral", position_integral));
next_state = struct("position_integral", pending_integral);
end

function validate_controller_state(controller_state, position_integral_limit)
if ~isstruct(controller_state) || ~isscalar(controller_state) || ...
        ~isequal(fieldnames(controller_state), {"position_integral"}) || ...
        ~isnumeric(controller_state.position_integral) || ...
        ~isreal(controller_state.position_integral) || ...
        ~isscalar(controller_state.position_integral) || ...
        ~isfinite(controller_state.position_integral) || ...
        abs(controller_state.position_integral) > position_integral_limit
    invalid_input( ...
        "controller_state must contain one bounded position integral.");
end
end

function validate_params(params)
if ~isstruct(params) || ~isscalar(params) || ...
        ~isfield(params, "state_gain") || ...
        ~isnumeric(params.state_gain) || ~isreal(params.state_gain) || ...
        ~isequal(size(params.state_gain), [1, 4]) || ...
        any(~isfinite(params.state_gain), "all") || ...
        ~isfield(params, "integral_gain") || ...
        ~isnumeric(params.integral_gain) || ~isreal(params.integral_gain) || ...
        ~isscalar(params.integral_gain) || ~isfinite(params.integral_gain) || ...
        ~isfield(params, "sample_time") || ...
        ~isnumeric(params.sample_time) || ~isreal(params.sample_time) || ...
        ~isscalar(params.sample_time) || ~isfinite(params.sample_time) || ...
        params.sample_time <= 0 || ...
        ~isfield(params, "position_integral_limit") || ...
        ~isnumeric(params.position_integral_limit) || ...
        ~isreal(params.position_integral_limit) || ...
        ~isscalar(params.position_integral_limit) || ...
        ~isfinite(params.position_integral_limit) || ...
        params.position_integral_limit <= 0
    invalid_input("params must contain finite valid LQI gains and limits.");
end
end

function validate_finite_scalar(value, value_name)
if ~isnumeric(value) || ~isreal(value) || ...
        ~isscalar(value) || ~isfinite(value)
    invalid_input(sprintf( ...
        "%s must be a finite real numeric scalar.", value_name));
end
end

function invalid_input(message)
error("twsbr:lqi:invalid_input", "%s", message);
end
