function validate_cascade_pid_timing(params)
%VALIDATE_CASCADE_PID_TIMING Enforce the frozen cascade simulation rates.

if ~isstruct(params) || ~isscalar(params) || ...
        ~all(isfield(params, ["plant_step", "sample_time"])) || ...
        abs(params.plant_step - 0.001) > 1e-15 || ...
        abs(params.sample_time - 0.01) > 1e-15
    error("twsbr:cascade_simulation:invalid_timing", ...
        "Cascade simulation requires plant_step=0.001 and sample_time=0.01.");
end
end
