function [cost, details] = control_objective(controller_name, vector, ...
        plant_params, study_config, objective, scenarios, base_seed)
%CONTROL_OBJECTIVE Evaluate one controller on the shared training set.

space = controller_parameter_space(controller_name);
validate_objective_config(objective);
objective.weights = double(objective.weights);
objective.scales = double(objective.scales);
objective.failure_penalty = double(objective.failure_penalty);
objective.invalid_penalty = double(objective.invalid_penalty);
validate_base_seed(base_seed);
base_seed = double(base_seed);
scenario_names = validate_training_scenarios(scenarios);
scenario_seeds = base_seed + (0:(numel(scenario_names) - 1)).';
scenario_details = repmat(empty_scenario_detail(), ...
    numel(scenario_names), 1);
details = struct( ...
    "controller", space.name, ...
    "seed", base_seed, ...
    "scenario_seeds", scenario_seeds, ...
    "scenarios", scenario_details, ...
    "failure_reason", "", ...
    "failed_scenario", "", ...
    "failed_index", 0);

for index = 1:numel(scenario_names)
    scenario_name = scenario_names(index);
    scenario = scenarios.(char(scenario_name));
    scenario_seed = scenario_seeds(index);
    try
        simulation = simulate_control_system(space.name, vector, ...
            plant_params, study_config, scenario, scenario_seed);
        metrics = calculate_control_metrics(simulation, scenario, ...
            plant_params);
    catch exception
        [is_candidate_error, failure_reason] = ...
            candidate_failure_reason(exception.identifier);
        if ~is_candidate_error
            rethrow(exception);
        end
        cost = objective.invalid_penalty;
        details.scenarios = scenario_details;
        details.failure_reason = failure_reason;
        details.failed_scenario = scenario_name;
        details.failed_index = index;
        return
    end

    deterministic_metrics = rmfield(metrics, ...
        ["controller_runtime_seconds", "mean_step_runtime_us"]);
    metric_values = objective_metric_values( ...
        deterministic_metrics, scenario, objective.metric_names);
    contributions = objective.weights .* ...
        (metric_values ./ objective.scales);
    base_cost = sum(contributions);
    penalty = 0.0;
    if ~deterministic_metrics.success
        penalty = objective.failure_penalty * ...
            (2 - simulation.survived_time / scenario.duration);
    end
    scenario_cost = base_cost + penalty;
    if ~isfinite(scenario_cost)
        cost = objective.invalid_penalty;
        details.scenarios = scenario_details;
        details.failure_reason = "nonfinite_objective_cost";
        details.failed_scenario = scenario_name;
        details.failed_index = index;
        return
    end

    scenario_details(index) = struct( ...
        "name", scenario_name, ...
        "seed", scenario_seed, ...
        "metrics", deterministic_metrics, ...
        "metric_values", metric_values, ...
        "contributions", contributions, ...
        "base_cost", base_cost, ...
        "failure_penalty", penalty, ...
        "scenario_cost", scenario_cost);
end

details.scenarios = scenario_details;
cost = mean([scenario_details.scenario_cost]);
if ~isfinite(cost)
    cost = objective.invalid_penalty;
    details.failure_reason = "nonfinite_objective_cost";
end
end

function values = objective_metric_values(metrics, scenario, metric_names)
values = zeros(numel(metric_names), 1);
for index = 1:numel(metric_names)
    metric_name = metric_names(index);
    if ~isfield(metrics, metric_name)
        error("twsbr:objective:invalid_config", ...
            "Objective metric names must identify available metrics.");
    end
    values(index) = metrics.(metric_name);
end
recovery_index = find(metric_names == ...
    "disturbance_recovery_time", 1);
if scenario.disturbance_end == 0 && ~isempty(recovery_index)
    values(recovery_index) = 0.0;
end
end

function [known, reason] = candidate_failure_reason(identifier)
known = true;
switch string(identifier)
    case "twsbr:controller:invalid_vector"
        reason = "invalid_controller_vector";
    case "twsbr:lqr:nonstabilizing_solution"
        reason = "nonstabilizing_lqr_candidate";
    case "twsbr:lqi:nonstabilizing_solution"
        reason = "nonstabilizing_lqi_candidate";
    case {"twsbr:fuzzy_pid:invalid_input", ...
            "twsbr:fuzzy:invalid_input"}
        reason = "invalid_fuzzy_candidate";
    case "twsbr:controller:nonfinite_output"
        reason = "nonfinite_controller_output";
    case "twsbr:metrics:invalid_input"
        reason = "invalid_candidate_metrics";
    otherwise
        known = false;
        reason = "";
end
end

function validate_objective_config(objective)
required_fields = ["metric_names", "weights", "scales", ...
    "failure_penalty", "invalid_penalty"];
expected_metrics = ["theta_itae"; "position_itae"; ...
    "control_energy"; "saturation_time"; "max_abs_theta_rad"; ...
    "disturbance_recovery_time"];
expected_weights = [0.25; 0.25; 0.15; 0.15; 0.10; 0.10];
expected_scales = [0.8; 8.0; 4.0; 1.0; deg2rad(10); 3.0];
expected_failure_penalty = 500.0;
expected_invalid_penalty = 1e6;
if ~isstruct(objective) || ~isscalar(objective) || ...
        ~all(isfield(objective, required_fields)) || ...
        ~isstring(objective.metric_names) || ...
        ~isequal(objective.metric_names, expected_metrics)
    invalid_config();
end
metric_count = numel(expected_metrics);
if ~isnumeric(objective.weights) || ~isreal(objective.weights) || ...
        ~isequal(size(objective.weights), [metric_count, 1]) || ...
        any(~isfinite(objective.weights)) || ...
        ~isequal(double(objective.weights), expected_weights) || ...
        ~isnumeric(objective.scales) || ~isreal(objective.scales) || ...
        ~isequal(size(objective.scales), [metric_count, 1]) || ...
        any(~isfinite(objective.scales)) || ...
        ~isequal(double(objective.scales), expected_scales) || ...
        ~is_positive_scalar(objective.failure_penalty) || ...
        double(objective.failure_penalty) ~= expected_failure_penalty || ...
        ~is_positive_scalar(objective.invalid_penalty) || ...
        double(objective.invalid_penalty) ~= expected_invalid_penalty
    invalid_config();
end
end

function names = validate_training_scenarios(scenarios)
names = ["T1_initial_tilt_5deg"; "T2_position_step_0p5m"; ...
    "T3_impulse_disturbance"];
if ~isstruct(scenarios) || ~isscalar(scenarios) || ...
        numel(fieldnames(scenarios)) ~= numel(names) || ...
        ~all(isfield(scenarios, cellstr(names)))
    invalid_scenarios();
end
required_fields = ["name", "split", "duration", ...
    "reference_start", "disturbance_end"];
for index = 1:numel(names)
    scenario = scenarios.(char(names(index)));
    if ~isstruct(scenario) || ~isscalar(scenario) || ...
            ~all(isfield(scenario, required_fields)) || ...
            ~is_text_equal(scenario.name, names(index)) || ...
            ~is_text_equal(scenario.split, "train") || ...
            ~is_positive_scalar(scenario.duration) || ...
            ~is_time_within_duration( ...
                scenario.reference_start, scenario.duration) || ...
            ~is_time_within_duration( ...
                scenario.disturbance_end, scenario.duration)
        invalid_scenarios();
    end
end
end

function validate_base_seed(base_seed)
if ~isnumeric(base_seed) || ~isreal(base_seed) || ...
        ~isscalar(base_seed) || ~isfinite(base_seed) || ...
        base_seed < 0 || base_seed > 2^32 - 3 || ...
        base_seed ~= floor(base_seed)
    error("twsbr:objective:invalid_seed", ...
        "Base seed must be an integer from 0 through 2^32-3.");
end
end

function valid = is_text_equal(value, expected)
valid = ((isstring(value) && isscalar(value) && ~ismissing(value)) || ...
    (ischar(value) && isrow(value))) && string(value) == expected;
end

function valid = is_time_within_duration(value, duration)
valid = isnumeric(value) && isreal(value) && isscalar(value) && ...
    isfinite(value) && value >= 0 && value <= duration;
end

function valid = is_positive_scalar(value)
valid = isnumeric(value) && isreal(value) && isscalar(value) && ...
    isfinite(value) && value > 0;
end

function detail = empty_scenario_detail()
detail = struct( ...
    "name", "", ...
    "seed", 0, ...
    "metrics", struct(), ...
    "metric_values", zeros(0, 1), ...
    "contributions", zeros(0, 1), ...
    "base_cost", 0.0, ...
    "failure_penalty", 0.0, ...
    "scenario_cost", 0.0);
end

function invalid_config()
error("twsbr:objective:invalid_config", ...
    "Objective configuration must contain the frozen finite definition.");
end

function invalid_scenarios()
error("twsbr:objective:invalid_scenarios", ...
    "Only the three canonical training scenarios may enter the objective.");
end