function config = monte_carlo_config(mode)
%MONTE_CARLO_CONFIG Return frozen uncertainty ranges for a study mode.

if nargin ~= 1 || ~is_valid_mode_value(mode)
    error("twsbr:study:invalid_mode", ...
        "Mode must be the scalar text value 'quick' or 'full'.");
end

mode = string(mode);
if mode == "quick"
    parameter_rho = 0.10;
elseif mode == "full"
    parameter_rho = 0.20;
else
    error("twsbr:study:invalid_mode", ...
        "Mode must be the scalar text value 'quick' or 'full'.");
end

config = struct( ...
    "parameter_rho", parameter_rho, ...
    "duration", 10.0, ...
    "initial_tilt_deg_range", [2.0, 8.0], ...
    "reference_range", [0.25, 1.0], ...
    "reference_start", 1.0, ...
    "force_range", [4.0, 9.0], ...
    "force_start_range", [3.0, 5.0], ...
    "force_duration_range", [0.10, 0.30], ...
    "constant_force_range", [-0.5, 0.5], ...
    "noise_std", [0.002; 0.01; deg2rad(0.15); deg2rad(0.5)]);
end

function valid = is_valid_mode_value(mode)
valid = (isstring(mode) && isscalar(mode) && ~ismissing(mode)) || ...
    (ischar(mode) && isrow(mode));
end
