function config = objective_config()
%OBJECTIVE_CONFIG Return the frozen control-study objective definition.

config = struct( ...
    "metric_names", ["theta_itae"; "position_itae"; ...
        "control_energy"; "saturation_time"; "max_abs_theta_rad"; ...
        "disturbance_recovery_time"], ...
    "weights", [0.25; 0.25; 0.15; 0.15; 0.10; 0.10], ...
    "scales", [0.8; 8.0; 4.0; 1.0; deg2rad(10); 3.0], ...
    "failure_penalty", 500.0, ...
    "invalid_penalty", 1e6);
end
