function [a_aug, b_aug] = twsbr_augmented_lqi_model( ...
        ad, bd, sample_time)
%TWSBR_AUGMENTED_LQI_MODEL Add a position-error integral state.

if ~isnumeric(ad) || ~isnumeric(bd) || ...
        ~isequal(size(ad), [4, 4]) || ~isequal(size(bd), [4, 1]) || ...
        ~isreal(ad) || ~isreal(bd) || ...
        any(~isfinite(ad), "all") || any(~isfinite(bd), "all")
    error("twsbr:lqi:invalid_discrete_model", ...
        "ad and bd must be finite real numeric 4-state matrices.");
end

if ~isnumeric(sample_time) || ~isscalar(sample_time) || ...
        ~isreal(sample_time) || ~isfinite(sample_time) || sample_time <= 0
    error("twsbr:lqi:invalid_sample_time", ...
        "sample_time must be a positive finite real numeric scalar.");
end

a_aug = [ad, zeros(4, 1); sample_time * [1, 0, 0, 0], 1];
b_aug = [bd; 0];
end
