function params = twsbr_params(overrides)
%TWSBR_PARAMS Return validated parameters for the TWSBR plant.

params = struct( ...
    "body_mass", 1.20, ...
    "wheel_mass_equiv", 0.30, ...
    "com_length", 0.18, ...
    "body_inertia", 0.025, ...
    "wheel_radius", 0.05, ...
    "viscous_damping", 0.05, ...
    "gravity", 9.81, ...
    "motor_force_gain", 12.0, ...
    "u_max", 1.0, ...
    "theta_fail_deg", 30.0, ...
    "x_limit", 5.0);

if nargin < 1
    overrides = struct();
end

if ~isstruct(overrides) || ~isscalar(overrides)
    error("twsbr:params:invalid_overrides", ...
        "Parameter overrides must be a scalar structure.");
end

override_fields = fieldnames(overrides);
valid_fields = fieldnames(params);
for index = 1:numel(override_fields)
    field_name = override_fields{index};
    if ~ismember(field_name, valid_fields)
        error("twsbr:params:unknown_field", ...
            "Unknown parameter field: %s", field_name);
    end
    params.(field_name) = overrides.(field_name);
end

positive_fields = { ...
    "body_mass", "wheel_mass_equiv", "com_length", ...
    "body_inertia", "wheel_radius", "gravity", ...
    "motor_force_gain", "u_max", "theta_fail_deg", "x_limit"};

for index = 1:numel(positive_fields)
    field_name = positive_fields{index};
    value = params.(field_name);
    if ~isnumeric(value) || ~isscalar(value) || ~isfinite(value) || value <= 0
        error("twsbr:params:invalid_value", ...
            "Parameter %s must be a positive finite scalar.", field_name);
    end
end

damping = params.viscous_damping;
if ~isnumeric(damping) || ~isscalar(damping) || ...
        ~isfinite(damping) || damping < 0
    error("twsbr:params:invalid_value", ...
        "Parameter viscous_damping must be a nonnegative finite scalar.");
end
end
